FULL_IDX_CATALOG = [
    {'code': 'AALI', 'symbol': 'AALI.JK', 'name': 'Astra Agro Lestari', 'sector': 'Agriculture & CPO'},
    {'code': 'ABDA', 'symbol': 'ABDA.JK', 'name': 'Asuransi Bina Dana Arta', 'sector': 'Financials'},
    {'code': 'ABMM', 'symbol': 'ABMM.JK', 'name': 'ABM Investama', 'sector': 'Energy & Mining'},
    {'code': 'ACES', 'symbol': 'ACES.JK', 'name': 'Aspirasi Hidup Indonesia (Ace Hardware)', 'sector': 'Consumer Cyclicals'},
    {'code': 'ACST', 'symbol': 'ACST.JK', 'name': 'Acset Indonusa', 'sector': 'Infrastructures'},
    {'code': 'ADCP', 'symbol': 'ADCP.JK', 'name': 'Adhi Commuter Properti', 'sector': 'Properties'},
    {'code': 'ADES', 'symbol': 'ADES.JK', 'name': 'Akasha Wira International', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'ADHI', 'symbol': 'ADHI.JK', 'name': 'Adhi Karya', 'sector': 'Infrastructures'},
    {'code': 'ADMF', 'symbol': 'ADMF.JK', 'name': 'Adira Dinamika Multi Finance', 'sector': 'Financials'},
    {'code': 'ADMG', 'symbol': 'ADMG.JK', 'name': 'Polychem Indonesia', 'sector': 'Basic Materials'},
    {'code': 'ADMR', 'symbol': 'ADMR.JK', 'name': 'Adaro Minerals Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'ADRO', 'symbol': 'ADRO.JK', 'name': 'Adaro Energy Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'AGAR', 'symbol': 'AGAR.JK', 'name': 'Asia Sejahtera Mina', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'AGII', 'symbol': 'AGII.JK', 'name': 'Samator Indo Gas', 'sector': 'Basic Materials'},
    {'code': 'AGRO', 'symbol': 'AGRO.JK', 'name': 'Bank Raya Indonesia', 'sector': 'Financials'},
    {'code': 'AGRS', 'symbol': 'AGRS.JK', 'name': 'Bank IBK Indonesia', 'sector': 'Financials'},
    {'code': 'AHAP', 'symbol': 'AHAP.JK', 'name': 'Asuransi Harta Aman Pratama', 'sector': 'Financials'},
    {'code': 'AIMS', 'symbol': 'AIMS.JK', 'name': 'Akbar Indo Makmur Stimec', 'sector': 'Energy & Mining'},
    {'code': 'AISA', 'symbol': 'AISA.JK', 'name': 'FKS Food Sejahtera', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'AKKU', 'symbol': 'AKKU.JK', 'name': 'Anugerah Kagum Karya Utama', 'sector': 'Consumer Cyclicals'},
    {'code': 'AKPI', 'symbol': 'AKPI.JK', 'name': 'Argha Karya Prima Industry', 'sector': 'Basic Materials'},
    {'code': 'AKRA', 'symbol': 'AKRA.JK', 'name': 'AKR Corporindo', 'sector': 'Energy & Mining'},
    {'code': 'AKSI', 'symbol': 'AKSI.JK', 'name': 'Mineral Sumberdaya Mandiri', 'sector': 'Energy & Mining'},
    {'code': 'ALDO', 'symbol': 'ALDO.JK', 'name': 'Alkindo Naratama', 'sector': 'Basic Materials'},
    {'code': 'ALKA', 'symbol': 'ALKA.JK', 'name': 'Alakasa Industrindo', 'sector': 'Basic Materials'},
    {'code': 'ALMI', 'symbol': 'ALMI.JK', 'name': 'Alumindo Light Metal Industry', 'sector': 'Basic Materials'},
    {'code': 'ALTO', 'symbol': 'ALTO.JK', 'name': 'Tri Banyan Tirta', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'AMAG', 'symbol': 'AMAG.JK', 'name': 'Asuransi Multi Artha Guna', 'sector': 'Financials'},
    {'code': 'AMAN', 'symbol': 'AMAN.JK', 'name': 'Makmur Berkah Amanda', 'sector': 'Properties'},
    {'code': 'AMAR', 'symbol': 'AMAR.JK', 'name': 'Bank Amar Indonesia', 'sector': 'Financials'},
    {'code': 'AMFG', 'symbol': 'AMFG.JK', 'name': 'Asahimas Flat Glass', 'sector': 'Basic Materials'},
    {'code': 'AMIN', 'symbol': 'AMIN.JK', 'name': 'Ateliers Mecaniques D Indonesie', 'sector': 'Industrials'},
    {'code': 'AMMN', 'symbol': 'AMMN.JK', 'name': 'Amman Mineral Internasional', 'sector': 'Basic Materials'},
    {'code': 'AMMS', 'symbol': 'AMMS.JK', 'name': 'Agung Menjangan Mas', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'AMOR', 'symbol': 'AMOR.JK', 'name': 'Ashmore Asset Management Indonesia', 'sector': 'Financials'},
    {'code': 'AMRT', 'symbol': 'AMRT.JK', 'name': 'Sumber Alfaria Trijaya (Alfamart)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'ANDI', 'symbol': 'ANDI.JK', 'name': 'Andira Agro', 'sector': 'Agriculture & CPO'},
    {'code': 'ANJT', 'symbol': 'ANJT.JK', 'name': 'Austindo Nusantara Jaya', 'sector': 'Agriculture & CPO'},
    {'code': 'ANTM', 'symbol': 'ANTM.JK', 'name': 'Aneka Tambang (Antam)', 'sector': 'Basic Materials'},
    {'code': 'APEX', 'symbol': 'APEX.JK', 'name': 'Apexindo Pratama Duta', 'sector': 'Energy & Mining'},
    {'code': 'APIC', 'symbol': 'APIC.JK', 'name': 'Pacific Strategic Financial', 'sector': 'Financials'},
    {'code': 'APII', 'symbol': 'APII.JK', 'name': 'Arita Prima Indonesia', 'sector': 'Industrials'},
    {'code': 'APLI', 'symbol': 'APLI.JK', 'name': 'Asiaplast Industries', 'sector': 'Basic Materials'},
    {'code': 'APLN', 'symbol': 'APLN.JK', 'name': 'Agung Podomoro Land', 'sector': 'Properties'},
    {'code': 'ARGO', 'symbol': 'ARGO.JK', 'name': 'Argo Pantes', 'sector': 'Consumer Cyclicals'},
    {'code': 'ARII', 'symbol': 'ARII.JK', 'name': 'Atlas Resources', 'sector': 'Energy & Mining'},
    {'code': 'ARKA', 'symbol': 'ARKA.JK', 'name': 'Arkha Jayanti Persada', 'sector': 'Industrials'},
    {'code': 'ARMY', 'symbol': 'ARMY.JK', 'name': 'Armidian Karyatama', 'sector': 'Properties'},
    {'code': 'ARNA', 'symbol': 'ARNA.JK', 'name': 'Arwana Citramulia', 'sector': 'Basic Materials'},
    {'code': 'ARTA', 'symbol': 'ARTA.JK', 'name': 'Arthavest', 'sector': 'Consumer Cyclicals'},
    {'code': 'ARTI', 'symbol': 'ARTI.JK', 'name': 'Ratu Prabu Energi', 'sector': 'Energy & Mining'},
    {'code': 'ARTO', 'symbol': 'ARTO.JK', 'name': 'Bank Jago', 'sector': 'Financials'},
    {'code': 'ASBI', 'symbol': 'ASBI.JK', 'name': 'Asuransi Bintang', 'sector': 'Financials'},
    {'code': 'ASDF', 'symbol': 'ASDF.JK', 'name': 'Astra Sedaya Finance', 'sector': 'Financials'},
    {'code': 'ASDM', 'symbol': 'ASDM.JK', 'name': 'Asuransi Dayin Mitra', 'sector': 'Financials'},
    {'code': 'ASGR', 'symbol': 'ASGR.JK', 'name': 'Astra Graphia', 'sector': 'Technology'},
    {'code': 'ASHA', 'symbol': 'ASHA.JK', 'name': 'Cilacap Samudera Fishing Industry', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'ASII', 'symbol': 'ASII.JK', 'name': 'Astra International', 'sector': 'Industrials'},
    {'code': 'ASJT', 'symbol': 'ASJT.JK', 'name': 'Asuransi Jasa Tania', 'sector': 'Financials'},
    {'code': 'ASLC', 'symbol': 'ASLC.JK', 'name': 'Autopedia Sukses Lestari', 'sector': 'Consumer Cyclicals'},
    {'code': 'ASMI', 'symbol': 'ASMI.JK', 'name': 'Asuransi Maximus Graha Persada', 'sector': 'Financials'},
    {'code': 'ASPI', 'symbol': 'ASPI.JK', 'name': 'Andalan Sakti Primaindo', 'sector': 'Properties'},
    {'code': 'ASPR', 'symbol': 'ASPR.JK', 'name': 'Astra Agro Lestari (Perkebunan)', 'sector': 'Agriculture & CPO'},
    {'code': 'ASRI', 'symbol': 'ASRI.JK', 'name': 'Alam Sutera Realty', 'sector': 'Properties'},
    {'code': 'ASRM', 'symbol': 'ASRM.JK', 'name': 'Asuransi Ramayana', 'sector': 'Financials'},
    {'code': 'ASSA', 'symbol': 'ASSA.JK', 'name': 'Adi Sarana Armada (Anteraja)', 'sector': 'Industrials'},
    {'code': 'ATAP', 'symbol': 'ATAP.JK', 'name': 'Trimitra Prawara Goldland', 'sector': 'Properties'},
    {'code': 'ATIC', 'symbol': 'ATIC.JK', 'name': 'Anabatic Technologies', 'sector': 'Technology'},
    {'code': 'ATLA', 'symbol': 'ATLA.JK', 'name': 'Atlantis Subsea Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'AUTO', 'symbol': 'AUTO.JK', 'name': 'Astra Otoparts', 'sector': 'Consumer Cyclicals'},
    {'code': 'AVIA', 'symbol': 'AVIA.JK', 'name': 'Avia Avian (Cat Avian)', 'sector': 'Basic Materials'},
    {'code': 'AWAN', 'symbol': 'AWAN.JK', 'name': 'Era Digital Media', 'sector': 'Technology'},
    {'code': 'AYAM', 'symbol': 'AYAM.JK', 'name': 'Janu Putra Sejahtera', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'AYLS', 'symbol': 'AYLS.JK', 'name': 'Agro Yasa Lestari', 'sector': 'Basic Materials'},
    {'code': 'BABP', 'symbol': 'BABP.JK', 'name': 'Bank MNC Internasional', 'sector': 'Financials'},
    {'code': 'BACA', 'symbol': 'BACA.JK', 'name': 'Bank Capital Indonesia', 'sector': 'Financials'},
    {'code': 'BAJA', 'symbol': 'BAJA.JK', 'name': 'Saranacentral Bajatama', 'sector': 'Basic Materials'},
    {'code': 'BALI', 'symbol': 'BALI.JK', 'name': 'Bali Towerindo Sentra', 'sector': 'Infrastructures'},
    {'code': 'BANK', 'symbol': 'BANK.JK', 'name': 'Bank Aladin Syariah', 'sector': 'Financials'},
    {'code': 'BAPO', 'symbol': 'BAPO.JK', 'name': 'Bhakti Agung Propertindo', 'sector': 'Properties'},
    {'code': 'BAPA', 'symbol': 'BAPA.JK', 'name': 'Bekasi Asri Pemula', 'sector': 'Properties'},
    {'code': 'BAPI', 'symbol': 'BAPI.JK', 'name': 'Bhisma Abadi Jaya', 'sector': 'Financials'},
    {'code': 'BBCA', 'symbol': 'BBCA.JK', 'name': 'Bank Central Asia', 'sector': 'Financials'},
    {'code': 'BBHI', 'symbol': 'BBHI.JK', 'name': 'Allo Bank Indonesia', 'sector': 'Financials'},
    {'code': 'BBKP', 'symbol': 'BBKP.JK', 'name': 'KB Bukopin', 'sector': 'Financials'},
    {'code': 'BBLD', 'symbol': 'BBLD.JK', 'name': 'Buana Finance', 'sector': 'Financials'},
    {'code': 'BBMD', 'symbol': 'BBMD.JK', 'name': 'Bank Mestika Dharma', 'sector': 'Financials'},
    {'code': 'BBNI', 'symbol': 'BBNI.JK', 'name': 'Bank Negara Indonesia (BNI)', 'sector': 'Financials'},
    {'code': 'BBRI', 'symbol': 'BBRI.JK', 'name': 'Bank Rakyat Indonesia (BRI)', 'sector': 'Financials'},
    {'code': 'BBRM', 'symbol': 'BBRM.JK', 'name': 'Pelayaran Nasional Bina Buana Raya', 'sector': 'Industrials'},
    {'code': 'BBSI', 'symbol': 'BBSI.JK', 'name': 'Krom Bank Indonesia', 'sector': 'Financials'},
    {'code': 'BBSS', 'symbol': 'BBSS.JK', 'name': 'Bumi Benowo Sukses Sejahtera', 'sector': 'Properties'},
    {'code': 'BBTN', 'symbol': 'BBTN.JK', 'name': 'Bank Tabungan Negara (BTN)', 'sector': 'Financials'},
    {'code': 'BBYB', 'symbol': 'BBYB.JK', 'name': 'Bank Neo Commerce', 'sector': 'Financials'},
    {'code': 'BCAP', 'symbol': 'BCAP.JK', 'name': 'MNC Kapital Indonesia', 'sector': 'Financials'},
    {'code': 'BCIC', 'symbol': 'BCIC.JK', 'name': 'Bank JTrust Indonesia', 'sector': 'Financials'},
    {'code': 'BCIP', 'symbol': 'BCIP.JK', 'name': 'Bumi Citra Permai', 'sector': 'Properties'},
    {'code': 'BDMN', 'symbol': 'BDMN.JK', 'name': 'Bank Danamon Indonesia', 'sector': 'Financials'},
    {'code': 'BEBS', 'symbol': 'BEBS.JK', 'name': 'Berkah Beton Sadaya', 'sector': 'Basic Materials'},
    {'code': 'BEEF', 'symbol': 'BEEF.JK', 'name': 'Estika Tata Tiara', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'BEER', 'symbol': 'BEER.JK', 'name': 'Jobi Multi Karya', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'BEKS', 'symbol': 'BEKS.JK', 'name': 'Bank Pembangunan Daerah Banten', 'sector': 'Financials'},
    {'code': 'BELI', 'symbol': 'BELI.JK', 'name': 'Global Digital Niaga (Blibli)', 'sector': 'Technology'},
    {'code': 'BELL', 'symbol': 'BELL.JK', 'name': 'Trisula Textile Industries', 'sector': 'Consumer Cyclicals'},
    {'code': 'BESS', 'symbol': 'BESS.JK', 'name': 'Batulicin Nusantara Maritim', 'sector': 'Industrials'},
    {'code': 'BEST', 'symbol': 'BEST.JK', 'name': 'Bekasi Fajar Industrial Estate', 'sector': 'Properties'},
    {'code': 'BFIN', 'symbol': 'BFIN.JK', 'name': 'BFI Finance Indonesia', 'sector': 'Financials'},
    {'code': 'BGTG', 'symbol': 'BGTG.JK', 'name': 'Bank Ganesha', 'sector': 'Financials'},
    {'code': 'BHAT', 'symbol': 'BHAT.JK', 'name': 'Bhakti Multi Artha', 'sector': 'Financials'},
    {'code': 'BHIT', 'symbol': 'BHIT.JK', 'name': 'MNC Asia Holding', 'sector': 'Financials'},
    {'code': 'BIKE', 'symbol': 'BIKE.JK', 'name': 'Sepeda Bersama Indonesia', 'sector': 'Consumer Cyclicals'},
    {'code': 'BIMA', 'symbol': 'BIMA.JK', 'name': 'Primarindo Asia Infrastructure', 'sector': 'Consumer Cyclicals'},
    {'code': 'BINA', 'symbol': 'BINA.JK', 'name': 'Bank Ina Perdana', 'sector': 'Financials'},
    {'code': 'BIPI', 'symbol': 'BIPI.JK', 'name': 'Astrindo Nusantara Infrastruktur', 'sector': 'Energy & Mining'},
    {'code': 'BIPP', 'symbol': 'BIPP.JK', 'name': 'Bhuwanatala Indah Permai', 'sector': 'Properties'},
    {'code': 'BIRD', 'symbol': 'BIRD.JK', 'name': 'Blue Bird', 'sector': 'Industrials'},
    {'code': 'BISI', 'symbol': 'BISI.JK', 'name': 'BISI International', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'BJBR', 'symbol': 'BJBR.JK', 'name': 'Bank Pembangunan Daerah Jawa Barat (BJB)', 'sector': 'Financials'},
    {'code': 'BJTM', 'symbol': 'BJTM.JK', 'name': 'Bank Pembangunan Daerah Jawa Timur (Bank Jatim)', 'sector': 'Financials'},
    {'code': 'BKDP', 'symbol': 'BKDP.JK', 'name': 'Bukit Darmo Property', 'sector': 'Properties'},
    {'code': 'BKSL', 'symbol': 'BKSL.JK', 'name': 'Sentul City', 'sector': 'Properties'},
    {'code': 'BKSW', 'symbol': 'BKSW.JK', 'name': 'Bank QNB Indonesia', 'sector': 'Financials'},
    {'code': 'BLTZ', 'symbol': 'BLTZ.JK', 'name': 'Graha Layar Prima (CGV)', 'sector': 'Consumer Cyclicals'},
    {'code': 'BLUE', 'symbol': 'BLUE.JK', 'name': 'Berkah Prima Perkasa', 'sector': 'Technology'},
    {'code': 'BMAS', 'symbol': 'BMAS.JK', 'name': 'Bank Maspion Indonesia', 'sector': 'Financials'},
    {'code': 'BMBL', 'symbol': 'BMBL.JK', 'name': 'Lavender Bina Cendikia', 'sector': 'Consumer Cyclicals'},
    {'code': 'BMHS', 'symbol': 'BMHS.JK', 'name': 'Bundamedik', 'sector': 'Healthcare'},
    {'code': 'BMRI', 'symbol': 'BMRI.JK', 'name': 'Bank Mandiri', 'sector': 'Financials'},
    {'code': 'BMSR', 'symbol': 'BMSR.JK', 'name': 'Bintang Mitra Semestaraya', 'sector': 'Basic Materials'},
    {'code': 'BMTR', 'symbol': 'BMTR.JK', 'name': 'Global Mediacom', 'sector': 'Consumer Cyclicals'},
    {'code': 'BNBR', 'symbol': 'BNBR.JK', 'name': 'Bakrie & Brothers', 'sector': 'Industrials'},
    {'code': 'BNGA', 'symbol': 'BNGA.JK', 'name': 'Bank CIMB Niaga', 'sector': 'Financials'},
    {'code': 'BNII', 'symbol': 'BNII.JK', 'name': 'Bank Maybank Indonesia', 'sector': 'Financials'},
    {'code': 'BNLI', 'symbol': 'BNLI.JK', 'name': 'Bank Permata', 'sector': 'Financials'},
    {'code': 'BOBA', 'symbol': 'BOBA.JK', 'name': 'Formosa Ingredient Factory', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'BOGA', 'symbol': 'BOGA.JK', 'name': 'Bintang Oto Global', 'sector': 'Consumer Cyclicals'},
    {'code': 'BOLA', 'symbol': 'BOLA.JK', 'name': 'Bali Bintang Sejahtera (Bali United)', 'sector': 'Consumer Cyclicals'},
    {'code': 'BOLT', 'symbol': 'BOLT.JK', 'name': 'Garuda Metalindo', 'sector': 'Consumer Cyclicals'},
    {'code': 'BOSS', 'symbol': 'BOSS.JK', 'name': 'Borneo Olah Sarana Sukses', 'sector': 'Energy & Mining'},
    {'code': 'BPFI', 'symbol': 'BPFI.JK', 'name': 'Batavia Prosperindo Finance', 'sector': 'Financials'},
    {'code': 'BPII', 'symbol': 'BPII.JK', 'name': 'Batavia Prosperindo Internasional', 'sector': 'Financials'},
    {'code': 'BPTR', 'symbol': 'BPTR.JK', 'name': 'Batavia Prosperindo Trans', 'sector': 'Industrials'},
    {'code': 'BRAM', 'symbol': 'BRAM.JK', 'name': 'Indo Kordsa', 'sector': 'Consumer Cyclicals'},
    {'code': 'BREN', 'symbol': 'BREN.JK', 'name': 'Barito Renewables Energy', 'sector': 'Infrastructures'},
    {'code': 'BRIS', 'symbol': 'BRIS.JK', 'name': 'Bank Syariah Indonesia (BSI)', 'sector': 'Financials'},
    {'code': 'BRMS', 'symbol': 'BRMS.JK', 'name': 'Bumi Resources Minerals', 'sector': 'Basic Materials'},
    {'code': 'BRNA', 'symbol': 'BRNA.JK', 'name': 'Berlina', 'sector': 'Basic Materials'},
    {'code': 'BRPT', 'symbol': 'BRPT.JK', 'name': 'Barito Pacific', 'sector': 'Basic Materials'},
    {'code': 'BSDE', 'symbol': 'BSDE.JK', 'name': 'Bumi Serpong Damai (BSD City)', 'sector': 'Properties'},
    {'code': 'BSIM', 'symbol': 'BSIM.JK', 'name': 'Bank Sinarmas', 'sector': 'Financials'},
    {'code': 'BSML', 'symbol': 'BSML.JK', 'name': 'Bintang Samudera Mandiri Lines', 'sector': 'Industrials'},
    {'code': 'BSSR', 'symbol': 'BSSR.JK', 'name': 'Baramulti Suksessarana', 'sector': 'Energy & Mining'},
    {'code': 'BSWD', 'symbol': 'BSWD.JK', 'name': 'Bank of India Indonesia', 'sector': 'Financials'},
    {'code': 'BTEK', 'symbol': 'BTEK.JK', 'name': 'Bumi Teknokultura Unggul', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'BTEL', 'symbol': 'BTEL.JK', 'name': 'Bakrie Telecom', 'sector': 'Telco & Infra'},
    {'code': 'BTON', 'symbol': 'BTON.JK', 'name': 'Betonjaya Manunggal', 'sector': 'Basic Materials'},
    {'code': 'BTPN', 'symbol': 'BTPN.JK', 'name': 'Bank SMBC Indonesia (BTPN)', 'sector': 'Financials'},
    {'code': 'BTPS', 'symbol': 'BTPS.JK', 'name': 'Bank BTPN Syariah', 'sector': 'Financials'},
    {'code': 'BUDD', 'symbol': 'BUDD.JK', 'name': 'Budi Starch & Sweetener', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'BUKA', 'symbol': 'BUKA.JK', 'name': 'Bukalapak.com', 'sector': 'Technology'},
    {'code': 'BUKK', 'symbol': 'BUKK.JK', 'name': 'Bukaka Teknik Utama', 'sector': 'Infrastructures'},
    {'code': 'BULL', 'symbol': 'BULL.JK', 'name': 'Buana Lintas Lautan', 'sector': 'Industrials'},
    {'code': 'BUMI', 'symbol': 'BUMI.JK', 'name': 'Bumi Resources', 'sector': 'Energy & Mining'},
    {'code': 'BUVA', 'symbol': 'BUVA.JK', 'name': 'Bukit Uluwatu Villa', 'sector': 'Consumer Cyclicals'},
    {'code': 'BVIC', 'symbol': 'BVIC.JK', 'name': 'Bank Victoria International', 'sector': 'Financials'},
    {'code': 'BWPT', 'symbol': 'BWPT.JK', 'name': 'Eagle High Plantations', 'sector': 'Agriculture & CPO'},
    {'code': 'BYAN', 'symbol': 'BYAN.JK', 'name': 'Bayan Resources', 'sector': 'Energy & Mining'},
    {'code': 'CAKK', 'symbol': 'CAKK.JK', 'name': 'Cahayaputra Asa Keramik', 'sector': 'Basic Materials'},
    {'code': 'CAMP', 'symbol': 'CAMP.JK', 'name': 'Campina Ice Cream Industry', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CANI', 'symbol': 'CANI.JK', 'name': 'Capitol Nusantara Indonesia', 'sector': 'Industrials'},
    {'code': 'CARE', 'symbol': 'CARE.JK', 'name': 'Metro Healthcare Indonesia', 'sector': 'Healthcare'},
    {'code': 'CARS', 'symbol': 'CARS.JK', 'name': 'Bintraco Dharma', 'sector': 'Consumer Cyclicals'},
    {'code': 'CASA', 'symbol': 'CASA.JK', 'name': 'Capital Financial Indonesia', 'sector': 'Financials'},
    {'code': 'CASH', 'symbol': 'CASH.JK', 'name': 'Cashlez Worldwide Indonesia', 'sector': 'Technology'},
    {'code': 'CASS', 'symbol': 'CASS.JK', 'name': 'Cardig Aero Services', 'sector': 'Industrials'},
    {'code': 'CBPE', 'symbol': 'CBPE.JK', 'name': 'Citra Buana Prasida', 'sector': 'Properties'},
    {'code': 'CBRE', 'symbol': 'CBRE.JK', 'name': 'Cakra Buana Resources Energi', 'sector': 'Industrials'},
    {'code': 'CBUT', 'symbol': 'CBUT.JK', 'name': 'Ceria Utama Abadi', 'sector': 'Basic Materials'},
    {'code': 'CCSI', 'symbol': 'CCSI.JK', 'name': 'Communication Cable Systems Indonesia', 'sector': 'Infrastructures'},
    {'code': 'CEKA', 'symbol': 'CEKA.JK', 'name': 'Wilmar Cahaya Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CENT', 'symbol': 'CENT.JK', 'name': 'Centratama Telekomunikasi Indonesia', 'sector': 'Telco & Infra'},
    {'code': 'CFIN', 'symbol': 'CFIN.JK', 'name': 'Clipan Finance Indonesia', 'sector': 'Financials'},
    {'code': 'CHIP', 'symbol': 'CHIP.JK', 'name': 'Pelita Teknologi Global', 'sector': 'Technology'},
    {'code': 'CINT', 'symbol': 'CINT.JK', 'name': 'Chitose Internasional', 'sector': 'Consumer Cyclicals'},
    {'code': 'CITA', 'symbol': 'CITA.JK', 'name': 'Cita Mineral Investindo', 'sector': 'Basic Materials'},
    {'code': 'CITY', 'symbol': 'CITY.JK', 'name': 'Natura City Developments', 'sector': 'Properties'},
    {'code': 'CLEO', 'symbol': 'CLEO.JK', 'name': 'Sariguna Primatirta (Air Cleo)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CLPI', 'symbol': 'CLPI.JK', 'name': 'Colorpak Indonesia', 'sector': 'Basic Materials'},
    {'code': 'CMNP', 'symbol': 'CMNP.JK', 'name': 'Citra Marga Nusaphala Persada', 'sector': 'Infrastructures'},
    {'code': 'CMRY', 'symbol': 'CMRY.JK', 'name': 'Cisarua Mountain Dairy (Cimory)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CNKO', 'symbol': 'CNKO.JK', 'name': 'Exploitasi Energi Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'CNMA', 'symbol': 'CNMA.JK', 'name': 'Nusantara Sejahtera Raya (Cinema XXI)', 'sector': 'Consumer Cyclicals'},
    {'code': 'CNTX', 'symbol': 'CNTX.JK', 'name': 'Century Textile Industry', 'sector': 'Consumer Cyclicals'},
    {'code': 'COAL', 'symbol': 'COAL.JK', 'name': 'Black Diamond Resources', 'sector': 'Energy & Mining'},
    {'code': 'COCO', 'symbol': 'COCO.JK', 'name': 'Wahana Interfood Nusantara', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CPIN', 'symbol': 'CPIN.JK', 'name': 'Charoen Pokphand Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CPRI', 'symbol': 'CPRI.JK', 'name': 'Capri Nusa Satu Properti', 'sector': 'Properties'},
    {'code': 'CPRO', 'symbol': 'CPRO.JK', 'name': 'Central Proteina Prima', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CRAB', 'symbol': 'CRAB.JK', 'name': 'Toba Surimi Industries', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'CRSN', 'symbol': 'CRSN.JK', 'name': 'Carsurin', 'sector': 'Industrials'},
    {'code': 'CSAP', 'symbol': 'CSAP.JK', 'name': 'Catur Sentosa Adiprana (Mitra10)', 'sector': 'Consumer Cyclicals'},
    {'code': 'CSIS', 'symbol': 'CSIS.JK', 'name': 'Cahayasakti Investindo Sukses', 'sector': 'Properties'},
    {'code': 'CSMI', 'symbol': 'CSMI.JK', 'name': 'Cipta Selera Murni', 'sector': 'Consumer Cyclicals'},
    {'code': 'CSRA', 'symbol': 'CSRA.JK', 'name': 'Cisadane Sawit Raya', 'sector': 'Agriculture & CPO'},
    {'code': 'CTBN', 'symbol': 'CTBN.JK', 'name': 'Citra Tubindo', 'sector': 'Energy & Mining'},
    {'code': 'CTRA', 'symbol': 'CTRA.JK', 'name': 'Ciputra Development', 'sector': 'Properties'},
    {'code': 'CTTH', 'symbol': 'CTTH.JK', 'name': 'Citatah', 'sector': 'Basic Materials'},
    {'code': 'CUAN', 'symbol': 'CUAN.JK', 'name': 'Petrindo Jaya Kreasi', 'sector': 'Energy & Mining'},
    {'code': 'CYBR', 'symbol': 'CYBR.JK', 'name': 'ITSEC Asia', 'sector': 'Technology'},
    {'code': 'DAAZ', 'symbol': 'DAAZ.JK', 'name': 'Daaz Bara Lestari', 'sector': 'Energy & Mining'},
    {'code': 'DADA', 'symbol': 'DADA.JK', 'name': 'Diamond Citra Propertindo', 'sector': 'Properties'},
    {'code': 'DART', 'symbol': 'DART.JK', 'name': 'Duta Anggada Realty', 'sector': 'Properties'},
    {'code': 'DAYA', 'symbol': 'DAYA.JK', 'name': 'Duta Intidaya (Watsons)', 'sector': 'Consumer Cyclicals'},
    {'code': 'DCII', 'symbol': 'DCII.JK', 'name': 'DCI Indonesia', 'sector': 'Technology'},
    {'code': 'DEAL', 'symbol': 'DEAL.JK', 'name': 'Dewata Freightinternational', 'sector': 'Industrials'},
    {'code': 'DEFI', 'symbol': 'DEFI.JK', 'name': 'Danasupra Erapacific', 'sector': 'Financials'},
    {'code': 'DEPO', 'symbol': 'DEPO.JK', 'name': 'Caturkarda Depo Bangunan', 'sector': 'Consumer Cyclicals'},
    {'code': 'DEWA', 'symbol': 'DEWA.JK', 'name': 'Darma Henwa', 'sector': 'Energy & Mining'},
    {'code': 'DFAM', 'symbol': 'DFAM.JK', 'name': 'Dafam Property Indonesia', 'sector': 'Properties'},
    {'code': 'DGIK', 'symbol': 'DGIK.JK', 'name': 'Nusa Konstruksi Enjiniring', 'sector': 'Infrastructures'},
    {'code': 'DGNS', 'symbol': 'DGNS.JK', 'name': 'Diagnos Laboratorium Utama', 'sector': 'Healthcare'},
    {'code': 'DIGI', 'symbol': 'DIGI.JK', 'name': 'Arkadia Digital Media', 'sector': 'Technology'},
    {'code': 'DILD', 'symbol': 'DILD.JK', 'name': 'Intiland Development', 'sector': 'Properties'},
    {'code': 'DIVA', 'symbol': 'DIVA.JK', 'name': 'Distribusi Voucher Nusantara', 'sector': 'Technology'},
    {'code': 'DKFT', 'symbol': 'DKFT.JK', 'name': 'Central Omega Resources', 'sector': 'Basic Materials'},
    {'code': 'DLTA', 'symbol': 'DLTA.JK', 'name': 'Delta Djakarta', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'DMAS', 'symbol': 'DMAS.JK', 'name': 'Puradelta Lestari (Kota Deltamas)', 'sector': 'Properties'},
    {'code': 'DMMX', 'symbol': 'DMMX.JK', 'name': 'Digital Mediatama Maxima', 'sector': 'Technology'},
    {'code': 'DMND', 'symbol': 'DMND.JK', 'name': 'Diamond Food Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'DNAR', 'symbol': 'DNAR.JK', 'name': 'Bank Oke Indonesia', 'sector': 'Financials'},
    {'code': 'DNET', 'symbol': 'DNET.JK', 'name': 'Indoritel Makmur Internasional (Indomaret)', 'sector': 'Consumer Cyclicals'},
    {'code': 'DOID', 'symbol': 'DOID.JK', 'name': 'Delta Dunia Makmur (BUMA)', 'sector': 'Energy & Mining'},
    {'code': 'DPNS', 'symbol': 'DPNS.JK', 'name': 'Duta Pertiwi Nusantara', 'sector': 'Basic Materials'},
    {'code': 'DPUM', 'symbol': 'DPUM.JK', 'name': 'Dua Putra Utama Makmur', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'DRMA', 'symbol': 'DRMA.JK', 'name': 'Dharma Polimetal', 'sector': 'Consumer Cyclicals'},
    {'code': 'DSFI', 'symbol': 'DSFI.JK', 'name': 'Dharma Samudera Fishing Industries', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'DSNG', 'symbol': 'DSNG.JK', 'name': 'Dharma Satya Nusantara', 'sector': 'Agriculture & CPO'},
    {'code': 'DSSA', 'symbol': 'DSSA.JK', 'name': 'Dian Swastatika Sentosa', 'sector': 'Energy & Mining'},
    {'code': 'DUCK', 'symbol': 'DUCK.JK', 'name': 'Jaya Bersama Indo (The Duck King)', 'sector': 'Consumer Cyclicals'},
    {'code': 'DUTI', 'symbol': 'DUTI.JK', 'name': 'Duta Pertiwi', 'sector': 'Properties'},
    {'code': 'DVLA', 'symbol': 'DVLA.JK', 'name': 'Darya-Varia Laboratoria', 'sector': 'Healthcare'},
    {'code': 'DWGL', 'symbol': 'DWGL.JK', 'name': 'Dwi Guna Laksana', 'sector': 'Energy & Mining'},
    {'code': 'DYAN', 'symbol': 'DYAN.JK', 'name': 'Dyandra Media International', 'sector': 'Consumer Cyclicals'},
    {'code': 'EAST', 'symbol': 'EAST.JK', 'name': 'Eastparc Hotel', 'sector': 'Consumer Cyclicals'},
    {'code': 'ECII', 'symbol': 'ECII.JK', 'name': 'Electronic City Indonesia', 'sector': 'Consumer Cyclicals'},
    {'code': 'EDGE', 'symbol': 'EDGE.JK', 'name': 'Indointernet', 'sector': 'Technology'},
    {'code': 'EKAD', 'symbol': 'EKAD.JK', 'name': 'Ekadharma International', 'sector': 'Basic Materials'},
    {'code': 'ELIT', 'symbol': 'ELIT.JK', 'name': 'Data Sinergitama Jaya (Elitery)', 'sector': 'Technology'},
    {'code': 'ELPI', 'symbol': 'ELPI.JK', 'name': 'Pelayaran Nasional Ekalya Purnamasari', 'sector': 'Industrials'},
    {'code': 'ELSA', 'symbol': 'ELSA.JK', 'name': 'Elnusa', 'sector': 'Energy & Mining'},
    {'code': 'ELTY', 'symbol': 'ELTY.JK', 'name': 'Bakrieland Development', 'sector': 'Properties'},
    {'code': 'EMAS', 'symbol': 'EMAS.JK', 'name': 'PT Merdeka Battery Materials (Nickel)', 'sector': 'Basic Materials'},
    {'code': 'EMDE', 'symbol': 'EMDE.JK', 'name': 'Megapolitan Developments', 'sector': 'Properties'},
    {'code': 'EMTK', 'symbol': 'EMTK.JK', 'name': 'Elang Mahkota Teknologi (Emtek)', 'sector': 'Technology'},
    {'code': 'ENAK', 'symbol': 'ENAK.JK', 'name': 'Champ Resto Indonesia (Gokana/Raa Cha)', 'sector': 'Consumer Cyclicals'},
    {'code': 'ENRG', 'symbol': 'ENRG.JK', 'name': 'Energi Mega Persada', 'sector': 'Energy & Mining'},
    {'code': 'ENVY', 'symbol': 'ENVY.JK', 'name': 'Envy Technologies Indonesia', 'sector': 'Technology'},
    {'code': 'EPMT', 'symbol': 'EPMT.JK', 'name': 'Enseval Putera Megatrading', 'sector': 'Healthcare'},
    {'code': 'ERAA', 'symbol': 'ERAA.JK', 'name': 'Erajaya Swasembada (iBox/Erafone)', 'sector': 'Consumer Cyclicals'},
    {'code': 'ERAL', 'symbol': 'ERAL.JK', 'name': 'Sinar Eka Selaras', 'sector': 'Consumer Cyclicals'},
    {'code': 'ERTX', 'symbol': 'ERTX.JK', 'name': 'Eratex Djaja', 'sector': 'Consumer Cyclicals'},
    {'code': 'ESIP', 'symbol': 'ESIP.JK', 'name': 'Sinergi Inti Plastindo', 'sector': 'Basic Materials'},
    {'code': 'ESSA', 'symbol': 'ESSA.JK', 'name': 'ESSA Industries Indonesia', 'sector': 'Basic Materials'},
    {'code': 'ESTA', 'symbol': 'ESTA.JK', 'name': 'Esta Multi Usaha', 'sector': 'Consumer Cyclicals'},
    {'code': 'ESTI', 'symbol': 'ESTI.JK', 'name': 'Ever Shine Tex', 'sector': 'Consumer Cyclicals'},
    {'code': 'ETWA', 'symbol': 'ETWA.JK', 'name': 'Eterindo Wahanatama', 'sector': 'Basic Materials'},
    {'code': 'EURO', 'symbol': 'EURO.JK', 'name': 'Estetika Tata Tiara (Food)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'EXCL', 'symbol': 'EXCL.JK', 'name': 'XL Axiata', 'sector': 'Telco & Infra'},
    {'code': 'FAPA', 'symbol': 'FAPA.JK', 'name': 'FAP Agro', 'sector': 'Agriculture & CPO'},
    {'code': 'FAST', 'symbol': 'FAST.JK', 'name': 'Fast Food Indonesia (KFC Indonesia)', 'sector': 'Consumer Cyclicals'},
    {'code': 'FASW', 'symbol': 'FASW.JK', 'name': 'Fajar Surya Wisesa', 'sector': 'Basic Materials'},
    {'code': 'FILM', 'symbol': 'FILM.JK', 'name': 'MD Pictures', 'sector': 'Consumer Cyclicals'},
    {'code': 'FIMP', 'symbol': 'FIMP.JK', 'name': 'Fimperkasa Utama', 'sector': 'Infrastructures'},
    {'code': 'FIRE', 'symbol': 'FIRE.JK', 'name': 'Alfa Energi Investama', 'sector': 'Energy & Mining'},
    {'code': 'FITT', 'symbol': 'FITT.JK', 'name': 'Hotel Fitra International', 'sector': 'Consumer Cyclicals'},
    {'code': 'FLMC', 'symbol': 'FLMC.JK', 'name': 'Falmaco Nonwoven Industri', 'sector': 'Basic Materials'},
    {'code': 'FMII', 'symbol': 'FMII.JK', 'name': 'Fortune Mate Indonesia', 'sector': 'Properties'},
    {'code': 'FOOD', 'symbol': 'FOOD.JK', 'name': 'Sentra Food Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'FORU', 'symbol': 'FORU.JK', 'name': 'Fortune Indonesia', 'sector': 'Consumer Cyclicals'},
    {'code': 'FPNI', 'symbol': 'FPNI.JK', 'name': 'Lotte Chemical Titan Nusantara', 'sector': 'Basic Materials'},
    {'code': 'FUJI', 'symbol': 'FUJI.JK', 'name': 'Fuji Finance Indonesia', 'sector': 'Financials'},
    {'code': 'GAMA', 'symbol': 'GAMA.JK', 'name': 'Aksara Global Investama', 'sector': 'Properties'},
    {'code': 'GDST', 'symbol': 'GDST.JK', 'name': 'Gunawan Dianjaya Steel', 'sector': 'Basic Materials'},
    {'code': 'GDYR', 'symbol': 'GDYR.JK', 'name': 'Goodyear Indonesia', 'sector': 'Consumer Cyclicals'},
    {'code': 'GEMA', 'symbol': 'GEMA.JK', 'name': 'Gema Grahasarana', 'sector': 'Industrials'},
    {'code': 'GEMS', 'symbol': 'GEMS.JK', 'name': 'Golden Energy Mines', 'sector': 'Energy & Mining'},
    {'code': 'GGRP', 'symbol': 'GGRP.JK', 'name': 'Gunung Raja Paksi', 'sector': 'Basic Materials'},
    {'code': 'GHON', 'symbol': 'GHON.JK', 'name': 'Gihon Telekomunikasi Indonesia', 'sector': 'Telco & Infra'},
    {'code': 'GIAA', 'symbol': 'GIAA.JK', 'name': 'Garuda Indonesia', 'sector': 'Industrials'},
    {'code': 'GJTL', 'symbol': 'GJTL.JK', 'name': 'Gajah Tunggal', 'sector': 'Consumer Cyclicals'},
    {'code': 'GLOB', 'symbol': 'GLOB.JK', 'name': 'Globe Kita Terang', 'sector': 'Technology'},
    {'code': 'GLVA', 'symbol': 'GLVA.JK', 'name': 'Galva Technologies', 'sector': 'Technology'},
    {'code': 'GMFI', 'symbol': 'GMFI.JK', 'name': 'Garuda Maintenance Facility Aero Asia', 'sector': 'Industrials'},
    {'code': 'GMTD', 'symbol': 'GMTD.JK', 'name': 'Gowa Makassar Tourism Development', 'sector': 'Properties'},
    {'code': 'GOLD', 'symbol': 'GOLD.JK', 'name': 'Visi Telekomunikasi Infrastruktur', 'sector': 'Telco & Infra'},
    {'code': 'GOLL', 'symbol': 'GOLL.JK', 'name': 'Golden Plantation', 'sector': 'Agriculture & CPO'},
    {'code': 'GOOD', 'symbol': 'GOOD.JK', 'name': 'Garudafood Putra Putri Jaya', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'GOTO', 'symbol': 'GOTO.JK', 'name': 'GoTo Gojek Tokopedia', 'sector': 'Technology'},
    {'code': 'GPRA', 'symbol': 'GPRA.JK', 'name': 'Perdana Gapuraprima', 'sector': 'Properties'},
    {'code': 'GPSO', 'symbol': 'GPSO.JK', 'name': 'Geoprima Solusi', 'sector': 'Industrials'},
    {'code': 'GRIA', 'symbol': 'GRIA.JK', 'name': 'Ingria Pratama Capitalindo', 'sector': 'Properties'},
    {'code': 'GRPH', 'symbol': 'GRPH.JK', 'name': 'Grahaprima Suksesmandiri', 'sector': 'Industrials'},
    {'code': 'GULA', 'symbol': 'GULA.JK', 'name': 'Aman Agrindo (Gula)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'GUNA', 'symbol': 'GUNA.JK', 'name': 'Gunanusa Eramandiri', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'GZCO', 'symbol': 'GZCO.JK', 'name': 'Gozco Plantations', 'sector': 'Agriculture & CPO'},
    {'code': 'HADE', 'symbol': 'HADE.JK', 'name': 'Himalaya Energi Perkasa', 'sector': 'Energy & Mining'},
    {'code': 'HAIS', 'symbol': 'HAIS.JK', 'name': 'Hasnur Internasional Shipping', 'sector': 'Industrials'},
    {'code': 'HAJJ', 'symbol': 'HAJJ.JK', 'name': 'Arsy Buana Travelindo', 'sector': 'Consumer Cyclicals'},
    {'code': 'HALO', 'symbol': 'HALO.JK', 'name': 'Haloni Jane (Sarung Tangan Medis)', 'sector': 'Healthcare'},
    {'code': 'HATM', 'symbol': 'HATM.JK', 'name': 'Habco Trans Maritima', 'sector': 'Industrials'},
    {'code': 'HBAT', 'symbol': 'HBAT.JK', 'name': 'Minahasa Membangun Hebat', 'sector': 'Properties'},
    {'code': 'HDFA', 'symbol': 'HDFA.JK', 'name': 'Radana Bhaskara Finance', 'sector': 'Financials'},
    {'code': 'HDIT', 'symbol': 'HDIT.JK', 'name': 'Hensel Davest Indonesia', 'sector': 'Technology'},
    {'code': 'HDTX', 'symbol': 'HDTX.JK', 'name': 'Panasia Indo Resources', 'sector': 'Consumer Cyclicals'},
    {'code': 'HEAL', 'symbol': 'HEAL.JK', 'name': 'Medikaloka Hermina (RS Hermina)', 'sector': 'Healthcare'},
    {'code': 'HELI', 'symbol': 'HELI.JK', 'name': 'Jaya Trishindo (Helicopter)', 'sector': 'Industrials'},
    {'code': 'HERO', 'symbol': 'HERO.JK', 'name': 'Hero Supermarket (IKEA Indonesia)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'HEXA', 'symbol': 'HEXA.JK', 'name': 'Hexindo Adiperkasa (Hitachi Heavy)', 'sector': 'Industrials'},
    {'code': 'HITS', 'symbol': 'HITS.JK', 'name': 'Humpuss Intermoda Transportasi', 'sector': 'Industrials'},
    {'code': 'HMSP', 'symbol': 'HMSP.JK', 'name': 'H.M. Sampoerna', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'HOKI', 'symbol': 'HOKI.JK', 'name': 'Buyung Poetra Sembada (Beras Topi Koki)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'HOME', 'symbol': 'HOME.JK', 'name': 'Hotel Mandarine Regency', 'sector': 'Consumer Cyclicals'},
    {'code': 'HOMI', 'symbol': 'HOMI.JK', 'name': 'Grand House Mulia', 'sector': 'Properties'},
    {'code': 'HOTL', 'symbol': 'HOTL.JK', 'name': 'Saraswati Griya Lestari', 'sector': 'Consumer Cyclicals'},
    {'code': 'HRME', 'symbol': 'HRME.JK', 'name': 'Menteng Heritage Realty', 'sector': 'Consumer Cyclicals'},
    {'code': 'HRTA', 'symbol': 'HRTA.JK', 'name': 'Hartadinata Abadi (Emas)', 'sector': 'Consumer Cyclicals'},
    {'code': 'HRUM', 'symbol': 'HRUM.JK', 'name': 'Harum Energy', 'sector': 'Energy & Mining'},
    {'code': 'HYGN', 'symbol': 'HYGN.JK', 'name': 'Ecocare Indo Pasifik', 'sector': 'Industrials'},
    {'code': 'IATA', 'symbol': 'IATA.JK', 'name': 'MNC Energy Investments', 'sector': 'Energy & Mining'},
    {'code': 'IBFN', 'symbol': 'IBFN.JK', 'name': 'Intan Baruprana Finance', 'sector': 'Financials'},
    {'code': 'IBOS', 'symbol': 'IBOS.JK', 'name': 'Indo Boga Sukses', 'sector': 'Consumer Cyclicals'},
    {'code': 'IBST', 'symbol': 'IBST.JK', 'name': 'Inti Bangun Sejahtera', 'sector': 'Telco & Infra'},
    {'code': 'ICBP', 'symbol': 'ICBP.JK', 'name': 'Indofood CBP Sukses Makmur (Indomie)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'ICON', 'symbol': 'ICON.JK', 'name': 'Island Concepts Indonesia', 'sector': 'Consumer Cyclicals'},
    {'code': 'IDEA', 'symbol': 'IDEA.JK', 'name': 'Idea Indonesia Akademi', 'sector': 'Consumer Cyclicals'},
    {'code': 'IDPR', 'symbol': 'IDPR.JK', 'name': 'Indonesia Pondasi Raya (Indopora)', 'sector': 'Infrastructures'},
    {'code': 'IFII', 'symbol': 'IFII.JK', 'name': 'Indonesia Fibreboard Industry', 'sector': 'Basic Materials'},
    {'code': 'IFSH', 'symbol': 'IFSH.JK', 'name': 'IFISHDECO (Nikel Mining)', 'sector': 'Basic Materials'},
    {'code': 'IGAR', 'symbol': 'IGAR.JK', 'name': 'Champion Pasific Indonesia', 'sector': 'Basic Materials'},
    {'code': 'IKAI', 'symbol': 'IKAI.JK', 'name': 'Intikeramik Alamasri Industri', 'sector': 'Basic Materials'},
    {'code': 'IKAN', 'symbol': 'IKAN.JK', 'name': 'Era Mandiri Cemerlang', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'IKBI', 'symbol': 'IKBI.JK', 'name': 'Sumi Indo Kabel', 'sector': 'Basic Materials'},
    {'code': 'IKPC', 'symbol': 'IKPC.JK', 'name': 'Indah Kiat Pulp & Paper', 'sector': 'Basic Materials'},
    {'code': 'IMAS', 'symbol': 'IMAS.JK', 'name': 'Indomobil Sukses Internasional', 'sector': 'Consumer Cyclicals'},
    {'code': 'IMJS', 'symbol': 'IMJS.JK', 'name': 'Indomobil Multi Jasa', 'sector': 'Financials'},
    {'code': 'IMPC', 'symbol': 'IMPC.JK', 'name': 'Impack Pratama Industri', 'sector': 'Basic Materials'},
    {'code': 'INAF', 'symbol': 'INAF.JK', 'name': 'Indofarma', 'sector': 'Healthcare'},
    {'code': 'INAI', 'symbol': 'INAI.JK', 'name': 'Indal Aluminium Industry', 'sector': 'Basic Materials'},
    {'code': 'INCF', 'symbol': 'INCF.JK', 'name': 'Indo Komoditi Korpora', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'INCI', 'symbol': 'INCI.JK', 'name': 'Intanwijaya Internasional', 'sector': 'Basic Materials'},
    {'code': 'INCO', 'symbol': 'INCO.JK', 'name': 'Vale Indonesia (Nikel)', 'sector': 'Basic Materials'},
    {'code': 'INDF', 'symbol': 'INDF.JK', 'name': 'Indofood Sukses Makmur', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'INDO', 'symbol': 'INDO.JK', 'name': 'Royalindo Investa Wijaya', 'sector': 'Properties'},
    {'code': 'INDR', 'symbol': 'INDR.JK', 'name': 'Indo-Rama Synthetics', 'sector': 'Consumer Cyclicals'},
    {'code': 'INDS', 'symbol': 'INDS.JK', 'name': 'Indospring', 'sector': 'Consumer Cyclicals'},
    {'code': 'INDX', 'symbol': 'INDX.JK', 'name': 'Tanah Laut', 'sector': 'Energy & Mining'},
    {'code': 'INDY', 'symbol': 'INDY.JK', 'name': 'Indika Energy', 'sector': 'Energy & Mining'},
    {'code': 'INKP', 'symbol': 'INKP.JK', 'name': 'Indah Kiat Pulp & Paper', 'sector': 'Basic Materials'},
    {'code': 'INNO', 'symbol': 'INNO.JK', 'name': 'Inocycle Technology Group', 'sector': 'Basic Materials'},
    {'code': 'INOV', 'symbol': 'INOV.JK', 'name': 'Inovisi Infracom', 'sector': 'Technology'},
    {'code': 'INPC', 'symbol': 'INPC.JK', 'name': 'Bank Artha Graha Internasional', 'sector': 'Financials'},
    {'code': 'INPP', 'symbol': 'INPP.JK', 'name': 'Indonesian Paradise Property', 'sector': 'Properties'},
    {'code': 'INPS', 'symbol': 'INPS.JK', 'name': 'Indah Prakasa Sentosa', 'sector': 'Industrials'},
    {'code': 'INRU', 'symbol': 'INRU.JK', 'name': 'Toba Pulp Lestari', 'sector': 'Basic Materials'},
    {'code': 'INTA', 'symbol': 'INTA.JK', 'name': 'Intraco Penta', 'sector': 'Industrials'},
    {'code': 'INTD', 'symbol': 'INTD.JK', 'name': 'Inter Delta', 'sector': 'Consumer Cyclicals'},
    {'code': 'INTP', 'symbol': 'INTP.JK', 'name': 'Indocement Tunggal Prakarsa (Semen Tiga Roda)', 'sector': 'Basic Materials'},
    {'code': 'IPAC', 'symbol': 'IPAC.JK', 'name': 'Sinergi Multi Lestarindo', 'sector': 'Basic Materials'},
    {'code': 'IPCC', 'symbol': 'IPCC.JK', 'name': 'Indonesia Kendaraan Terminal (Pelindo)', 'sector': 'Industrials'},
    {'code': 'IPCM', 'symbol': 'IPCM.JK', 'name': 'Jasa Armada Indonesia', 'sector': 'Industrials'},
    {'code': 'IPPE', 'symbol': 'IPPE.JK', 'name': 'Indo Pureco Pratama', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'IPTV', 'symbol': 'IPTV.JK', 'name': 'MNC Vision Networks', 'sector': 'Consumer Cyclicals'},
    {'code': 'IRRA', 'symbol': 'IRRA.JK', 'name': 'Itama Ranoraya (Alat Kesehatan)', 'sector': 'Healthcare'},
    {'code': 'ISAP', 'symbol': 'ISAP.JK', 'name': 'Isra Presisi Indonesia', 'sector': 'Industrials'},
    {'code': 'ISAT', 'symbol': 'ISAT.JK', 'name': 'Indosat Ooredoo Hutchison', 'sector': 'Telco & Infra'},
    {'code': 'ISSP', 'symbol': 'ISSP.JK', 'name': 'Steel Pipe Industry of Indonesia (Spindo)', 'sector': 'Basic Materials'},
    {'code': 'ITIC', 'symbol': 'ITIC.JK', 'name': 'Indonesian Tobacco', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'ITMA', 'symbol': 'ITMA.JK', 'name': 'Sumber Energi Andalan', 'sector': 'Energy & Mining'},
    {'code': 'ITMG', 'symbol': 'ITMG.JK', 'name': 'Indo Tambangraya Megah', 'sector': 'Energy & Mining'},
    {'code': 'JARR', 'symbol': 'JARR.JK', 'name': 'Jhonlin Agro Raya', 'sector': 'Agriculture & CPO'},
    {'code': 'JAST', 'symbol': 'JAST.JK', 'name': 'Jasnita Telekomindo', 'sector': 'Telco & Infra'},
    {'code': 'JATI', 'symbol': 'JATI.JK', 'name': 'Informasi Teknologi Indonesia', 'sector': 'Technology'},
    {'code': 'JAWA', 'symbol': 'JAWA.JK', 'name': 'Jaya Agra Wattie', 'sector': 'Agriculture & CPO'},
    {'code': 'JAYA', 'symbol': 'JAYA.JK', 'name': 'Armada Berjaya Trans', 'sector': 'Industrials'},
    {'code': 'JECC', 'symbol': 'JECC.JK', 'name': 'Jembo Cable Company', 'sector': 'Basic Materials'},
    {'code': 'JGLE', 'symbol': 'JGLE.JK', 'name': 'Graha Andrasentra Propertindo (The Jungle)', 'sector': 'Consumer Cyclicals'},
    {'code': 'JIHD', 'symbol': 'JIHD.JK', 'name': 'Jakarta International Hotels & Development', 'sector': 'Consumer Cyclicals'},
    {'code': 'JKON', 'symbol': 'JKON.JK', 'name': 'Jaya Konstruksi Manggala Pratama', 'sector': 'Infrastructures'},
    {'code': 'JMAS', 'symbol': 'JMAS.JK', 'name': 'Asuransi Jiwa Syariah Jasa Mitra Abadi', 'sector': 'Financials'},
    {'code': 'JPFA', 'symbol': 'JPFA.JK', 'name': 'Japfa Comfeed Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'JRPT', 'symbol': 'JRPT.JK', 'name': 'Jaya Real Property (Bintaro Jaya)', 'sector': 'Properties'},
    {'code': 'JSMR', 'symbol': 'JSMR.JK', 'name': 'Jasa Marga (Persero)', 'sector': 'Infrastructures'},
    {'code': 'JSPT', 'symbol': 'JSPT.JK', 'name': 'Jakarta Setiabudi Internasional', 'sector': 'Consumer Cyclicals'},
    {'code': 'JTPE', 'symbol': 'JTPE.JK', 'name': 'Jasuindo Tiga Perkasa', 'sector': 'Industrials'},
    {'code': 'KAEF', 'symbol': 'KAEF.JK', 'name': 'Kimia Farma', 'sector': 'Healthcare'},
    {'code': 'KARW', 'symbol': 'KARW.JK', 'name': 'ICTSI Jasa Prima', 'sector': 'Industrials'},
    {'code': 'KAYU', 'symbol': 'KAYU.JK', 'name': 'Darmi Bersaudara', 'sector': 'Basic Materials'},
    {'code': 'KBAG', 'symbol': 'KBAG.JK', 'name': 'Karya Bersama Anugerah', 'sector': 'Properties'},
    {'code': 'KBLI', 'symbol': 'KBLI.JK', 'name': 'KMI Wire and Cable', 'sector': 'Basic Materials'},
    {'code': 'KBLM', 'symbol': 'KBLM.JK', 'name': 'Kabelindo Murni', 'sector': 'Basic Materials'},
    {'code': 'KBLV', 'symbol': 'KBLV.JK', 'name': 'First Media', 'sector': 'Telco & Infra'},
    {'code': 'KDSI', 'symbol': 'KDSI.JK', 'name': 'Kedawung Setia Industrial', 'sector': 'Consumer Cyclicals'},
    {'code': 'KEEN', 'symbol': 'KEEN.JK', 'name': 'Kencana Energi Lestari (EBT)', 'sector': 'Infrastructures'},
    {'code': 'KEJU', 'symbol': 'KEJU.JK', 'name': 'Mulia Boga Raya (Keju Prochiz)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'KIAS', 'symbol': 'KIAS.JK', 'name': 'Keramika Indonesia Assosiasi', 'sector': 'Basic Materials'},
    {'code': 'KICI', 'symbol': 'KICI.JK', 'name': 'Kedaung Indah Can', 'sector': 'Consumer Cyclicals'},
    {'code': 'KIJA', 'symbol': 'KIJA.JK', 'name': 'Kawasan Industri Jababeka', 'sector': 'Properties'},
    {'code': 'KING', 'symbol': 'KING.JK', 'name': 'Hoffmen Cleanindo', 'sector': 'Industrials'},
    {'code': 'KINO', 'symbol': 'KINO.JK', 'name': 'Kino Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'KIOS', 'symbol': 'KIOS.JK', 'name': 'Kioson Komersial Indonesia', 'sector': 'Technology'},
    {'code': 'KKGI', 'symbol': 'KKGI.JK', 'name': 'Resource Alam Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'KLAS', 'symbol': 'KLAS.JK', 'name': 'Pelayaran Kurnia Lautan Semesta', 'sector': 'Industrials'},
    {'code': 'KLBF', 'symbol': 'KLBF.JK', 'name': 'Kalbe Farma', 'sector': 'Healthcare'},
    {'code': 'KLIN', 'symbol': 'KLIN.JK', 'name': 'Wisrita Multi Solusi', 'sector': 'Industrials'},
    {'code': 'KMDS', 'symbol': 'KMDS.JK', 'name': 'Kurniamitra Duta Sentosa', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'KMTR', 'symbol': 'KMTR.JK', 'name': 'Kirana Megatara (Karet)', 'sector': 'Basic Materials'},
    {'code': 'KOBX', 'symbol': 'KOBX.JK', 'name': 'Kobexindo Tractors', 'sector': 'Industrials'},
    {'code': 'KOIN', 'symbol': 'KOIN.JK', 'name': 'Kokoh Inti Arebama', 'sector': 'Basic Materials'},
    {'code': 'KOKA', 'symbol': 'KOKA.JK', 'name': 'Koka Indonesia', 'sector': 'Infrastructures'},
    {'code': 'KONI', 'symbol': 'KONI.JK', 'name': 'Perdana Bangun Pusaka', 'sector': 'Consumer Cyclicals'},
    {'code': 'KOPI', 'symbol': 'KOPI.JK', 'name': 'Mitra Tirta Buwana', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'KOTA', 'symbol': 'KOTA.JK', 'name': 'DMS Propertindo', 'sector': 'Properties'},
    {'code': 'KPAL', 'symbol': 'KPAL.JK', 'name': 'Steadfast Marine', 'sector': 'Industrials'},
    {'code': 'KPAS', 'symbol': 'KPAS.JK', 'name': 'Cottonindo Ariesta', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'KPIG', 'symbol': 'KPIG.JK', 'name': 'MNC Land', 'sector': 'Properties'},
    {'code': 'KRAH', 'symbol': 'KRAH.JK', 'name': 'Grand Kartech', 'sector': 'Industrials'},
    {'code': 'KRAS', 'symbol': 'KRAS.JK', 'name': 'Krakatau Steel (Persero)', 'sector': 'Basic Materials'},
    {'code': 'KREN', 'symbol': 'KREN.JK', 'name': 'Quantum Clovera Investama', 'sector': 'Technology'},
    {'code': 'KRYA', 'symbol': 'KRYA.JK', 'name': 'Bangun Karya Perkasa Jaya', 'sector': 'Infrastructures'},
    {'code': 'KTIC', 'symbol': 'KTIC.JK', 'name': 'Keramika Indonesia (Ceramic)', 'sector': 'Basic Materials'},
    {'code': 'KTOR', 'symbol': 'KTOR.JK', 'name': 'Pelayaran Tamarin Samudra', 'sector': 'Energy & Mining'},
    {'code': 'LION', 'symbol': 'LION.JK', 'name': 'Lion Metal Works', 'sector': 'Basic Materials'},
    {'code': 'LMAS', 'symbol': 'LMAS.JK', 'name': 'Limas Indonesia Makmur', 'sector': 'Technology'},
    {'code': 'LMAX', 'symbol': 'LMAX.JK', 'name': 'Lupromax Pelumas Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'LMSH', 'symbol': 'LMSH.JK', 'name': 'Lionmesh Prima', 'sector': 'Basic Materials'},
    {'code': 'LPCK', 'symbol': 'LPCK.JK', 'name': 'Lippo Cikarang', 'sector': 'Properties'},
    {'code': 'LPGI', 'symbol': 'LPGI.JK', 'name': 'Lippo General Insurance', 'sector': 'Financials'},
    {'code': 'LPIN', 'symbol': 'LPIN.JK', 'name': 'Multi Prima Sejahtera', 'sector': 'Consumer Cyclicals'},
    {'code': 'LPKR', 'symbol': 'LPKR.JK', 'name': 'Lippo Karawaci', 'sector': 'Properties'},
    {'code': 'LPLI', 'symbol': 'LPLI.JK', 'name': 'Star Pacific', 'sector': 'Consumer Cyclicals'},
    {'code': 'LPPS', 'symbol': 'LPPS.JK', 'name': 'Lippo Securities', 'sector': 'Financials'},
    {'code': 'LRNA', 'symbol': 'LRNA.JK', 'name': 'Eka Sari Lorena Transport', 'sector': 'Industrials'},
    {'code': 'LSIP', 'symbol': 'LSIP.JK', 'name': 'PP London Sumatra Indonesia', 'sector': 'Agriculture & CPO'},
    {'code': 'LTLS', 'symbol': 'LTLS.JK', 'name': 'Lautan Luas (Kimia)', 'sector': 'Basic Materials'},
    {'code': 'LUCK', 'symbol': 'LUCK.JK', 'name': 'Sentral Mitra Informatika', 'sector': 'Technology'},
    {'code': 'LUCY', 'symbol': 'LUCY.JK', 'name': 'Lima Dua Lima Tiga (Lucy in the Sky)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MABA', 'symbol': 'MABA.JK', 'name': 'Marga Abhinaya Abadi', 'sector': 'Consumer Cyclicals'},
    {'code': 'MAGP', 'symbol': 'MAGP.JK', 'name': 'Multi Agro Gemilang Plantation', 'sector': 'Agriculture & CPO'},
    {'code': 'MAHA', 'symbol': 'MAHA.JK', 'name': 'Mandiri Herindo Adiperkasa', 'sector': 'Energy & Mining'},
    {'code': 'MAIN', 'symbol': 'MAIN.JK', 'name': 'Malindo Feedmill', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MAPA', 'symbol': 'MAPA.JK', 'name': 'MAP Aktif Adiperkasa (Sports Station/Foot Locker)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MAPB', 'symbol': 'MAPB.JK', 'name': 'MAP Boga Adiperkasa (Starbucks Indonesia/Subway)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MAPI', 'symbol': 'MAPI.JK', 'name': 'Mitra Adiperkasa (Zara/Sephora/Sogo)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MARI', 'symbol': 'MARI.JK', 'name': 'Mahaka Radio Integra (Gen FM/Jak FM)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MARK', 'symbol': 'MARK.JK', 'name': 'Mark Dynamics Indonesia (Cetakan Sarung Tangan)', 'sector': 'Industrials'},
    {'code': 'MASA', 'symbol': 'MASA.JK', 'name': 'Multistrada Arah Sarana (Ban Corsa/Achilles)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MASB', 'symbol': 'MASB.JK', 'name': 'Bank Multiarta Sentosa', 'sector': 'Financials'},
    {'code': 'MAXI', 'symbol': 'MAXI.JK', 'name': 'Maxindo Karya Anugerah', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MAYA', 'symbol': 'MAYA.JK', 'name': 'Bank Mayapada Internasional', 'sector': 'Financials'},
    {'code': 'MBAP', 'symbol': 'MBAP.JK', 'name': 'Mitrabara Adiperdana', 'sector': 'Energy & Mining'},
    {'code': 'MBMA', 'symbol': 'MBMA.JK', 'name': 'Merdeka Battery Materials (Nickel HPAL)', 'sector': 'Basic Materials'},
    {'code': 'MBSS', 'symbol': 'MBSS.JK', 'name': 'Mitrabahtera Segara Sejati', 'sector': 'Industrials'},
    {'code': 'MBTO', 'symbol': 'MBTO.JK', 'name': 'Martina Berto (Sariayu Martha Tilaar)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MCAS', 'symbol': 'MCAS.JK', 'name': 'M Cash Integrasi', 'sector': 'Technology'},
    {'code': 'MCOL', 'symbol': 'MCOL.JK', 'name': 'Prima Andalan Mandiri', 'sector': 'Energy & Mining'},
    {'code': 'MCOR', 'symbol': 'MCOR.JK', 'name': 'Bank China Construction Bank Indonesia', 'sector': 'Financials'},
    {'code': 'MDIA', 'symbol': 'MDIA.JK', 'name': 'Intermedia Capital (ANTV)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MDKA', 'symbol': 'MDKA.JK', 'name': 'Merdeka Copper Gold (Tujuh Bukit)', 'sector': 'Basic Materials'},
    {'code': 'MDKI', 'symbol': 'MDKI.JK', 'name': 'Emdeki Utama', 'sector': 'Basic Materials'},
    {'code': 'MDLN', 'symbol': 'MDLN.JK', 'name': 'Modernland Realty (Kota Modern)', 'sector': 'Properties'},
    {'code': 'MDRN', 'symbol': 'MDRN.JK', 'name': 'Modern Internasional', 'sector': 'Consumer Cyclicals'},
    {'code': 'MEDC', 'symbol': 'MEDC.JK', 'name': 'Medco Energi Internasional', 'sector': 'Energy & Mining'},
    {'code': 'MEGA', 'symbol': 'MEGA.JK', 'name': 'Bank Mega', 'sector': 'Financials'},
    {'code': 'MENN', 'symbol': 'MENN.JK', 'name': 'Menn Teknologi Indonesia', 'sector': 'Technology'},
    {'code': 'MERK', 'symbol': 'MERK.JK', 'name': 'Merck Indonesia (Farmasi)', 'sector': 'Healthcare'},
    {'code': 'META', 'symbol': 'META.JK', 'name': 'Nusantara Infrastructure (Tol BSD)', 'sector': 'Infrastructures'},
    {'code': 'MFIN', 'symbol': 'MFIN.JK', 'name': 'Mandala Multifinance', 'sector': 'Financials'},
    {'code': 'MFMI', 'symbol': 'MFMI.JK', 'name': 'Multifiling Mitra Indonesia', 'sector': 'Industrials'},
    {'code': 'MGLV', 'symbol': 'MGLV.JK', 'name': 'Panca Anugrah Wisesa (Megaliving)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MGNA', 'symbol': 'MGNA.JK', 'name': 'Magna Investama Mandiri', 'sector': 'Financials'},
    {'code': 'MGRO', 'symbol': 'MGRO.JK', 'name': 'Mahkota Group (CPO/Kelapa Sawit)', 'sector': 'Agriculture & CPO'},
    {'code': 'MICE', 'symbol': 'MICE.JK', 'name': 'Multi Indocitra (Pigeon Indonesia)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MIDI', 'symbol': 'MIDI.JK', 'name': 'Midi Utama Indonesia (Alfamidi)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MIKA', 'symbol': 'MIKA.JK', 'name': 'Mitra Keluarga Karyasehat (RS Mitra Keluarga)', 'sector': 'Healthcare'},
    {'code': 'MIRA', 'symbol': 'MIRA.JK', 'name': 'Mitra Rajawali Banjaran', 'sector': 'Industrials'},
    {'code': 'MITI', 'symbol': 'MITI.JK', 'name': 'Mitra Investindo', 'sector': 'Energy & Mining'},
    {'code': 'MKAP', 'symbol': 'MKAP.JK', 'name': 'Multikarya Asia Pasifik Raya', 'sector': 'Energy & Mining'},
    {'code': 'MKNT', 'symbol': 'MKNT.JK', 'name': 'Mitra Komunikasi Nusantara', 'sector': 'Telco & Infra'},
    {'code': 'MKPI', 'symbol': 'MKPI.JK', 'name': 'Metropolitan Kentjana (Pondok Indah Mall)', 'sector': 'Properties'},
    {'code': 'MKTR', 'symbol': 'MKTR.JK', 'name': 'Menthobi Karyatama Raya', 'sector': 'Agriculture & CPO'},
    {'code': 'MLBI', 'symbol': 'MLBI.JK', 'name': 'Multi Bintang Indonesia (Bir Bintang)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MLIA', 'symbol': 'MLIA.JK', 'name': 'Mulia Industrindo (Kaca Mulia)', 'sector': 'Basic Materials'},
    {'code': 'MLPL', 'symbol': 'MLPL.JK', 'name': 'Multipolar', 'sector': 'Technology'},
    {'code': 'MLPT', 'symbol': 'MLPT.JK', 'name': 'Multipolar Technology', 'sector': 'Technology'},
    {'code': 'MMIX', 'symbol': 'MMIX.JK', 'name': 'Multi Medika Internasional', 'sector': 'Healthcare'},
    {'code': 'MMLP', 'symbol': 'MMLP.JK', 'name': 'Mega Manunggal Property', 'sector': 'Properties'},
    {'code': 'MNCN', 'symbol': 'MNCN.JK', 'name': 'Media Nusantara Citra (RCTI/MNCTV/GTV)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MOLI', 'symbol': 'MOLI.JK', 'name': 'Madusari Murni Indah (Molindo Etanol)', 'sector': 'Basic Materials'},
    {'code': 'MPMX', 'symbol': 'MPMX.JK', 'name': 'Mitra Pinasthika Mustika (Motor Honda Jatim)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MPOW', 'symbol': 'MPOW.JK', 'name': 'Megapower Makmur (Pembangkit Listrik)', 'sector': 'Infrastructures'},
    {'code': 'MPPA', 'symbol': 'MPPA.JK', 'name': 'Matahari Putra Prima (Hypermart)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MPRO', 'symbol': 'MPRO.JK', 'name': 'Maha Properti Indonesia', 'sector': 'Properties'},
    {'code': 'MRAT', 'symbol': 'MRAT.JK', 'name': 'Mustika Ratu (Jamu & Kosmetik)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MREI', 'symbol': 'MREI.JK', 'name': 'Maskapai Reasuransi Indonesia (Marein)', 'sector': 'Financials'},
    {'code': 'MSIN', 'symbol': 'MSIN.JK', 'name': 'MNC Digital Entertainment', 'sector': 'Consumer Cyclicals'},
    {'code': 'MSKY', 'symbol': 'MSKY.JK', 'name': 'MNC Sky Vision (Indovision)', 'sector': 'Consumer Cyclicals'},
    {'code': 'MTDL', 'symbol': 'MTDL.JK', 'name': 'Metrodata Electronics', 'sector': 'Technology'},
    {'code': 'MTEL', 'symbol': 'MTEL.JK', 'name': 'Dayamitra Telekomunikasi (Mitratel)', 'sector': 'Telco & Infra'},
    {'code': 'MTFN', 'symbol': 'MTFN.JK', 'name': 'Capitalinc Investment', 'sector': 'Energy & Mining'},
    {'code': 'MTLA', 'symbol': 'MTLA.JK', 'name': 'Metropolitan Land (Metland)', 'sector': 'Properties'},
    {'code': 'MTMH', 'symbol': 'MTMH.JK', 'name': 'Murni Sadar (RS Murni Teguh)', 'sector': 'Healthcare'},
    {'code': 'MTPS', 'symbol': 'MTPS.JK', 'name': 'Mitra Pemuda', 'sector': 'Infrastructures'},
    {'code': 'MTRA', 'symbol': 'MTRA.JK', 'name': 'Mitra Transaksi Indonesia', 'sector': 'Technology'},
    {'code': 'MTSM', 'symbol': 'MTSM.JK', 'name': 'Metro Realty', 'sector': 'Properties'},
    {'code': 'MUTU', 'symbol': 'MUTU.JK', 'name': 'Mutuagung Lestari (Sertifikasi Karbon)', 'sector': 'Industrials'},
    {'code': 'MYOH', 'symbol': 'MYOH.JK', 'name': 'Samindo Resources', 'sector': 'Energy & Mining'},
    {'code': 'MYOR', 'symbol': 'MYOR.JK', 'name': 'Mayora Indah (Kopiko/Beng-Beng)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'MYRX', 'symbol': 'MYRX.JK', 'name': 'Hanson International', 'sector': 'Properties'},
    {'code': 'MYTX', 'symbol': 'MYTX.JK', 'name': 'Asia Pasific Investama', 'sector': 'Consumer Cyclicals'},
    {'code': 'NANO', 'symbol': 'NANO.JK', 'name': 'Nanotech Indonesia Global', 'sector': 'Technology'},
    {'code': 'NASA', 'symbol': 'NASA.JK', 'name': 'Andalan Perkasa Abadi', 'sector': 'Energy & Mining'},
    {'code': 'NASI', 'symbol': 'NASI.JK', 'name': 'Wahana Inti Makmur (Beras)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'NATO', 'symbol': 'NATO.JK', 'name': 'Surya Permata Andalan', 'sector': 'Properties'},
    {'code': 'NAYZ', 'symbol': 'NAYZ.JK', 'name': 'Hassana Boga Sejahtera (Makanan Bayi)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'NCKL', 'symbol': 'NCKL.JK', 'name': 'Trimegah Bangun Persada (Harita Nickel)', 'sector': 'Basic Materials'},
    {'code': 'NEST', 'symbol': 'NEST.JK', 'name': 'Mustika Ratu Tbk (Herbal)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'NETV', 'symbol': 'NETV.JK', 'name': 'Net Visi Media (NET TV)', 'sector': 'Consumer Cyclicals'},
    {'code': 'NFCX', 'symbol': 'NFCX.JK', 'name': 'NFC Indonesia (Volta Motor Listrik)', 'sector': 'Technology'},
    {'code': 'NICE', 'symbol': 'NICE.JK', 'name': 'Adhi Kartiko Pratama (Nikel)', 'sector': 'Basic Materials'},
    {'code': 'NICK', 'symbol': 'NICK.JK', 'name': 'Charnic Capital', 'sector': 'Financials'},
    {'code': 'NICL', 'symbol': 'NICL.JK', 'name': 'PAM Mineral (Nikel)', 'sector': 'Basic Materials'},
    {'code': 'NIKL', 'symbol': 'NIKL.JK', 'name': 'Pelat Timah Nusantara (Latinusa)', 'sector': 'Basic Materials'},
    {'code': 'NINE', 'symbol': 'NINE.JK', 'name': 'Techno9 Indonesia', 'sector': 'Technology'},
    {'code': 'NISP', 'symbol': 'NISP.JK', 'name': 'Bank OCBC NISP', 'sector': 'Financials'},
    {'code': 'NOBU', 'symbol': 'NOBU.JK', 'name': 'Bank Nationalnobu', 'sector': 'Financials'},
    {'code': 'NPGF', 'symbol': 'NPGF.JK', 'name': 'Nusa Palapa Gemilang', 'sector': 'Basic Materials'},
    {'code': 'NRCA', 'symbol': 'NRCA.JK', 'name': 'Nusa Raya Cipta (Konstruksi)', 'sector': 'Infrastructures'},
    {'code': 'NSSS', 'symbol': 'NSSS.JK', 'name': 'Nusantara Sawit Sejahtera', 'sector': 'Agriculture & CPO'},
    {'code': 'NTBK', 'symbol': 'NTBK.JK', 'name': 'Nusantara Pelabuhan Handal', 'sector': 'Industrials'},
    {'code': 'NUSA', 'symbol': 'NUSA.JK', 'name': 'Sinergi Megah Internusa', 'sector': 'Consumer Cyclicals'},
    {'code': 'NZIA', 'symbol': 'NZIA.JK', 'name': 'Nusantara Alfindo', 'sector': 'Properties'},
    {'code': 'OASA', 'symbol': 'OASA.JK', 'name': 'Maharaksa Biru Energi', 'sector': 'Infrastructures'},
    {'code': 'OBMD', 'symbol': 'OBMD.JK', 'name': 'OBM Drilchem', 'sector': 'Basic Materials'},
    {'code': 'OILS', 'symbol': 'OILS.JK', 'name': 'Indo Oil Perkasa', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'OKAS', 'symbol': 'OKAS.JK', 'name': 'Ancora Indonesia Resources', 'sector': 'Energy & Mining'},
    {'code': 'OLIV', 'symbol': 'OLIV.JK', 'name': 'Victoria Care Indonesia (Herborist)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'OMRE', 'symbol': 'OMRE.JK', 'name': 'Indonesia Prima Property', 'sector': 'Properties'},
    {'code': 'OPMS', 'symbol': 'OPMS.JK', 'name': 'Optima Prima Metal Sinergi', 'sector': 'Basic Materials'},
    {'code': 'PACK', 'symbol': 'PACK.JK', 'name': 'Solusi Kemasan Digital (FlexyPack)', 'sector': 'Basic Materials'},
    {'code': 'PADA', 'symbol': 'PADA.JK', 'name': 'Personel Alih Daya (Outsourcing)', 'sector': 'Industrials'},
    {'code': 'PADW', 'symbol': 'PADW.JK', 'name': 'Duta Perkasa Abadi', 'sector': 'Basic Materials'},
    {'code': 'PAMG', 'symbol': 'PAMG.JK', 'name': 'Bima Sakti Pertiwi (Mal Pekanbaru)', 'sector': 'Properties'},
    {'code': 'PANI', 'symbol': 'PANI.JK', 'name': 'Pantai Indah Kapuk Dua (PIK 2)', 'sector': 'Properties'},
    {'code': 'PANR', 'symbol': 'PANR.JK', 'name': 'Panorama Sentrawisata (Tour & Travel)', 'sector': 'Consumer Cyclicals'},
    {'code': 'PANS', 'symbol': 'PANS.JK', 'name': 'Panin Sekuritas', 'sector': 'Financials'},
    {'code': 'PBID', 'symbol': 'PBID.JK', 'name': 'Panca Budi Idaman (Plastik Wayang)', 'sector': 'Basic Materials'},
    {'code': 'PBRX', 'symbol': 'PBRX.JK', 'name': 'Pan Brothers (Garmen)', 'sector': 'Consumer Cyclicals'},
    {'code': 'PBSA', 'symbol': 'PBSA.JK', 'name': 'Paramita Bangun Sarana', 'sector': 'Infrastructures'},
    {'code': 'PCAR', 'symbol': 'PCAR.JK', 'name': 'Prima Cakrawala Abadi', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'PDES', 'symbol': 'PDES.JK', 'name': 'Destinasi Tirta Nusantara (Panorama Destination)', 'sector': 'Consumer Cyclicals'},
    {'code': 'PDPP', 'symbol': 'PDPP.JK', 'name': 'Primadaya Plastisindo', 'sector': 'Basic Materials'},
    {'code': 'PEGE', 'symbol': 'PEGE.JK', 'name': 'Panca Global Kapital', 'sector': 'Financials'},
    {'code': 'PEHA', 'symbol': 'PEHA.JK', 'name': 'Phapros (Antimo/Anelat)', 'sector': 'Healthcare'},
    {'code': 'PEVE', 'symbol': 'PEVE.JK', 'name': 'Penta Valent', 'sector': 'Healthcare'},
    {'code': 'PGAS', 'symbol': 'PGAS.JK', 'name': 'Perusahaan Gas Negara (PGN)', 'sector': 'Energy & Mining'},
    {'code': 'PGEO', 'symbol': 'PGEO.JK', 'name': 'Pertamina Geothermal Energy', 'sector': 'Infrastructures'},
    {'code': 'PGLI', 'symbol': 'PGLI.JK', 'name': 'Pembangunan Graha Lestari Indah', 'sector': 'Consumer Cyclicals'},
    {'code': 'PGUN', 'symbol': 'PGUN.JK', 'name': 'Pradiksi Gunatama', 'sector': 'Agriculture & CPO'},
    {'code': 'PICO', 'symbol': 'PICO.JK', 'name': 'Pelangi Indah Canindo', 'sector': 'Basic Materials'},
    {'code': 'PIMH', 'symbol': 'PIMH.JK', 'name': 'Puradelta Industri & Mineral', 'sector': 'Basic Materials'},
    {'code': 'PIPE', 'symbol': 'PIPE.JK', 'name': 'Wahana Vinyl Nusantara', 'sector': 'Basic Materials'},
    {'code': 'PJAA', 'symbol': 'PJAA.JK', 'name': 'Pembangunan Jaya Ancol (Dufan Ancol)', 'sector': 'Consumer Cyclicals'},
    {'code': 'PKPK', 'symbol': 'PKPK.JK', 'name': 'Perdana Karya Perkasa', 'sector': 'Energy & Mining'},
    {'code': 'PLAS', 'symbol': 'PLAS.JK', 'name': 'Polaris Investama', 'sector': 'Financials'},
    {'code': 'PLIN', 'symbol': 'PLIN.JK', 'name': 'Plaza Indonesia Realty', 'sector': 'Properties'},
    {'code': 'PMJS', 'symbol': 'PMJS.JK', 'name': 'Putra Mandiri Jembar', 'sector': 'Consumer Cyclicals'},
    {'code': 'PMMP', 'symbol': 'PMMP.JK', 'name': 'Panca Mitra Multiperdana (Udang Beku)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'PNBN', 'symbol': 'PNBN.JK', 'name': 'Bank Pan Indonesia (Bank Panin)', 'sector': 'Financials'},
    {'code': 'PNBS', 'symbol': 'PNBS.JK', 'name': 'Bank Panin Dubai Syariah', 'sector': 'Financials'},
    {'code': 'PNGO', 'symbol': 'PNGO.JK', 'name': 'Pinago Utama', 'sector': 'Agriculture & CPO'},
    {'code': 'PNIN', 'symbol': 'PNIN.JK', 'name': 'Paninvest', 'sector': 'Financials'},
    {'code': 'PNLF', 'symbol': 'PNLF.JK', 'name': 'Panin Financial', 'sector': 'Financials'},
    {'code': 'PNSE', 'symbol': 'PNSE.JK', 'name': 'Pudjiadi & Sons (Hotel Marbella)', 'sector': 'Consumer Cyclicals'},
    {'code': 'POLA', 'symbol': 'POLA.JK', 'name': 'Pool Advista Finance', 'sector': 'Financials'},
    {'code': 'POLI', 'symbol': 'POLI.JK', 'name': 'Pollux Investasi Internasional', 'sector': 'Properties'},
    {'code': 'POLL', 'symbol': 'POLL.JK', 'name': 'Pollux Properties Indonesia', 'sector': 'Properties'},
    {'code': 'POLU', 'symbol': 'POLU.JK', 'name': 'Golden Flower', 'sector': 'Consumer Cyclicals'},
    {'code': 'POLY', 'symbol': 'POLY.JK', 'name': 'Asia Pacific Fibers', 'sector': 'Basic Materials'},
    {'code': 'POOL', 'symbol': 'POOL.JK', 'name': 'Pool Advista Indonesia', 'sector': 'Financials'},
    {'code': 'PORT', 'symbol': 'PORT.JK', 'name': 'Nusantara Pelabuhan Handal (IPC)', 'sector': 'Industrials'},
    {'code': 'POSA', 'symbol': 'POSA.JK', 'name': 'Bliss Properti Indonesia', 'sector': 'Properties'},
    {'code': 'POWR', 'symbol': 'POWR.JK', 'name': 'Cikarang Listrindo (PLTU)', 'sector': 'Infrastructures'},
    {'code': 'PPGL', 'symbol': 'PPGL.JK', 'name': 'Prima Globalindo Logistik', 'sector': 'Industrials'},
    {'code': 'PPRE', 'symbol': 'PPRE.JK', 'name': 'PP Presisi', 'sector': 'Infrastructures'},
    {'code': 'PPRO', 'symbol': 'PPRO.JK', 'name': 'PP Properti', 'sector': 'Properties'},
    {'code': 'PRAS', 'symbol': 'PRAS.JK', 'name': 'Prima Alloy Steel Universal', 'sector': 'Consumer Cyclicals'},
    {'code': 'PRDA', 'symbol': 'PRDA.JK', 'name': 'Prodia Widyahusada (Lab Prodia)', 'sector': 'Healthcare'},
    {'code': 'PRIM', 'symbol': 'PRIM.JK', 'name': 'Royal Prima (RS Royal Prima)', 'sector': 'Healthcare'},
    {'code': 'PRSF', 'symbol': 'PRSF.JK', 'name': 'Pratama Abadi Nusa Industri', 'sector': 'Properties'},
    {'code': 'PSAB', 'symbol': 'PSAB.JK', 'name': 'J Resources Asia Pasifik (Emas)', 'sector': 'Basic Materials'},
    {'code': 'PSDN', 'symbol': 'PSDN.JK', 'name': 'Prasidha Aneka Niaga', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'PSGO', 'symbol': 'PSGO.JK', 'name': 'Palma Serasih', 'sector': 'Agriculture & CPO'},
    {'code': 'PSKT', 'symbol': 'PSKT.JK', 'name': 'Red Planet Indonesia', 'sector': 'Consumer Cyclicals'},
    {'code': 'PSSI', 'symbol': 'PSSI.JK', 'name': 'Pelita Samudera Shipping', 'sector': 'Industrials'},
    {'code': 'PTBA', 'symbol': 'PTBA.JK', 'name': 'Bukit Asam', 'sector': 'Energy & Mining'},
    {'code': 'PTDU', 'symbol': 'PTDU.JK', 'name': 'Djasa Ubersakti', 'sector': 'Infrastructures'},
    {'code': 'PTIS', 'symbol': 'PTIS.JK', 'name': 'Indo Straits', 'sector': 'Energy & Mining'},
    {'code': 'PTMP', 'symbol': 'PTMP.JK', 'name': 'Mitra Pack', 'sector': 'Industrials'},
    {'code': 'PTPP', 'symbol': 'PTPP.JK', 'name': 'PP (Persero)', 'sector': 'Infrastructures'},
    {'code': 'PTPS', 'symbol': 'PTPS.JK', 'name': 'Pulau Subur', 'sector': 'Agriculture & CPO'},
    {'code': 'PTRO', 'symbol': 'PTRO.JK', 'name': 'Petrosea (Mining Contractor)', 'sector': 'Energy & Mining'},
    {'code': 'PTSN', 'symbol': 'PTSN.JK', 'name': 'Sat Nusapersada (Perakitan Handphone)', 'sector': 'Technology'},
    {'code': 'PTSP', 'symbol': 'PTSP.JK', 'name': 'Pioneerindo Gourmet International (CFC)', 'sector': 'Consumer Cyclicals'},
    {'code': 'PUDP', 'symbol': 'PUDP.JK', 'name': 'Pudjiadi Prestige', 'sector': 'Properties'},
    {'code': 'PURA', 'symbol': 'PURA.JK', 'name': 'Pura Delta Lestari', 'sector': 'Properties'},
    {'code': 'PURE', 'symbol': 'PURE.JK', 'name': 'Trinitan Metals and Minerals', 'sector': 'Basic Materials'},
    {'code': 'PURI', 'symbol': 'PURI.JK', 'name': 'Puri Global Sukses', 'sector': 'Properties'},
    {'code': 'PWON', 'symbol': 'PWON.JK', 'name': 'Pakuwon Jati (Gandaria City/Kota Kasablanka/Tunjungan Plaza)', 'sector': 'Properties'},
    {'code': 'PYFA', 'symbol': 'PYFA.JK', 'name': 'Pyridam Farma', 'sector': 'Healthcare'},
    {'code': 'PZZA', 'symbol': 'PZZA.JK', 'name': 'Sarimelati Kencana (Pizza Hut Indonesia)', 'sector': 'Consumer Cyclicals'},
    {'code': 'RAAM', 'symbol': 'RAAM.JK', 'name': 'Tripar Multivision Plus (MVP)', 'sector': 'Consumer Cyclicals'},
    {'code': 'RAFI', 'symbol': 'RAFI.JK', 'name': 'Sari Kreasi Perdana (Kebab Baba Rafi)', 'sector': 'Consumer Cyclicals'},
    {'code': 'RAJA', 'symbol': 'RAJA.JK', 'name': 'Rukun Raharja (Gas Infrastructure)', 'sector': 'Energy & Mining'},
    {'code': 'RALS', 'symbol': 'RALS.JK', 'name': 'Ramayana Lestari Sentosa', 'sector': 'Consumer Cyclicals'},
    {'code': 'RAMA', 'symbol': 'RAMA.JK', 'name': 'Ramayana Sentosa Internasional', 'sector': 'Consumer Cyclicals'},
    {'code': 'RANC', 'symbol': 'RANC.JK', 'name': 'Supra Boga Lestari (Ranch Market/Farmers Market)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'RBMS', 'symbol': 'RBMS.JK', 'name': 'Ristia Bintang Mahkotasejati', 'sector': 'Properties'},
    {'code': 'RCCC', 'symbol': 'RCCC.JK', 'name': 'Roda Vivatex', 'sector': 'Consumer Cyclicals'},
    {'code': 'RDTX', 'symbol': 'RDTX.JK', 'name': 'Roda Vivatex (Sewa Gedung RDTX)', 'sector': 'Properties'},
    {'code': 'REAL', 'symbol': 'REAL.JK', 'name': 'Repower Asia Indonesia', 'sector': 'Properties'},
    {'code': 'RELF', 'symbol': 'RELF.JK', 'name': 'Graha Mitra Asia', 'sector': 'Properties'},
    {'code': 'RELI', 'symbol': 'RELI.JK', 'name': 'Reliance Sekuritas Indonesia', 'sector': 'Financials'},
    {'code': 'RGAS', 'symbol': 'RGAS.JK', 'name': 'Kian Santang Muliatama', 'sector': 'Energy & Mining'},
    {'code': 'RICY', 'symbol': 'RICY.JK', 'name': 'Ricky Putra Globalindo (Celana Rider)', 'sector': 'Consumer Cyclicals'},
    {'code': 'RIGS', 'symbol': 'RIGS.JK', 'name': 'Rig Tenders Indonesia', 'sector': 'Energy & Mining'},
    {'code': 'RIMO', 'symbol': 'RIMO.JK', 'name': 'Rimo International Lestari', 'sector': 'Properties'},
    {'code': 'RISE', 'symbol': 'RISE.JK', 'name': 'Jaya Sukses Makmur Sentosa (Tanrise Property)', 'sector': 'Properties'},
    {'code': 'RMKE', 'symbol': 'RMKE.JK', 'name': 'RMK Energy (Logistik Batubara)', 'sector': 'Energy & Mining'},
    {'code': 'RMKO', 'symbol': 'RMKO.JK', 'name': 'Royaltama Mulia Kontraktorindo', 'sector': 'Energy & Mining'},
    {'code': 'ROCK', 'symbol': 'ROCK.JK', 'name': 'Rockfields Properti Indonesia', 'sector': 'Properties'},
    {'code': 'RODA', 'symbol': 'RODA.JK', 'name': 'Pikko Land Development', 'sector': 'Properties'},
    {'code': 'RONY', 'symbol': 'RONY.JK', 'name': 'Omni Inovasi Rekatama', 'sector': 'Technology'},
    {'code': 'ROTI', 'symbol': 'ROTI.JK', 'name': 'Nippon Indosari Corpindo (Sari Roti)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'RSCH', 'symbol': 'RSCH.JK', 'name': 'Charlie Hospital Semarang', 'sector': 'Healthcare'},
    {'code': 'RSGK', 'symbol': 'RSGK.JK', 'name': 'Kedoya Adyaraya (RS Grha Kedoya)', 'sector': 'Healthcare'},
    {'code': 'RUIS', 'symbol': 'RUIS.JK', 'name': 'Radiant Utama Interinsco', 'sector': 'Energy & Mining'},
    {'code': 'RUNS', 'symbol': 'RUNS.JK', 'name': 'Global Sukses Solusi (RUN System)', 'sector': 'Technology'},
    {'code': 'SAFE', 'symbol': 'SAFE.JK', 'name': 'Steady Safe', 'sector': 'Industrials'},
    {'code': 'SAME', 'symbol': 'SAME.JK', 'name': 'Sarana Meditama Metropolitan (RS EMC Healthcare)', 'sector': 'Healthcare'},
    {'code': 'SAMF', 'symbol': 'SAMF.JK', 'name': 'Saraswanti Anugerah Makmur (Pupuk)', 'sector': 'Basic Materials'},
    {'code': 'SAPX', 'symbol': 'SAPX.JK', 'name': 'Satria Antaran Prima (SAP Express)', 'sector': 'Industrials'},
    {'code': 'SATU', 'symbol': 'SATU.JK', 'name': 'Kota Satu Properti', 'sector': 'Properties'},
    {'code': 'SBAT', 'symbol': 'SBAT.JK', 'name': 'Sejahtera Bintang Abadi Textile', 'sector': 'Consumer Cyclicals'},
    {'code': 'SBMA', 'symbol': 'SBMA.JK', 'name': 'Surya Biru Murni Acetylene (Gas Industri)', 'sector': 'Basic Materials'},
    {'code': 'SCCO', 'symbol': 'SCCO.JK', 'name': 'Supreme Cable Manufacturing & Commerce (Sucaco)', 'sector': 'Basic Materials'},
    {'code': 'SCMA', 'symbol': 'SCMA.JK', 'name': 'Surya Citra Media (SCTV/Indosiar/Vidio)', 'sector': 'Consumer Cyclicals'},
    {'code': 'SCNP', 'symbol': 'SCNP.JK', 'name': 'Selaras Citra Nusantara Perkasa (Turbo/Philips)', 'sector': 'Consumer Cyclicals'},
    {'code': 'SDMU', 'symbol': 'SDMU.JK', 'name': 'Sidomulyo Selaras', 'sector': 'Industrials'},
    {'code': 'SDPC', 'symbol': 'SDPC.JK', 'name': 'Millennium Pharmacon International', 'sector': 'Healthcare'},
    {'code': 'SDRA', 'symbol': 'SDRA.JK', 'name': 'Bank Woori Saudara Indonesia 1906', 'sector': 'Financials'},
    {'code': 'SEMA', 'symbol': 'SEMA.JK', 'name': 'Semacom Integrated', 'sector': 'Industrials'},
    {'code': 'SFAN', 'symbol': 'SFAN.JK', 'name': 'Surya Fajar Capital', 'sector': 'Financials'},
    {'code': 'SGER', 'symbol': 'SGER.JK', 'name': 'Sumber Global Energy (Trader Batubara/Nikel)', 'sector': 'Energy & Mining'},
    {'code': 'SGRO', 'symbol': 'SGRO.JK', 'name': 'Sampoerna Agro', 'sector': 'Agriculture & CPO'},
    {'code': 'SHID', 'symbol': 'SHID.JK', 'name': 'Hotel Sahid Jaya International', 'sector': 'Consumer Cyclicals'},
    {'code': 'SHIP', 'symbol': 'SHIP.JK', 'name': 'Sillo Maritime Perdana', 'sector': 'Energy & Mining'},
    {'code': 'SICO', 'symbol': 'SICO.JK', 'name': 'Sigma Energy Compressindo', 'sector': 'Energy & Mining'},
    {'code': 'SIDO', 'symbol': 'SIDO.JK', 'name': 'Industri Jamu dan Farmasi Sido Muncul (Tolak Angin)', 'sector': 'Healthcare'},
    {'code': 'SILO', 'symbol': 'SILO.JK', 'name': 'Siloam International Hospitals (RS Siloam)', 'sector': 'Healthcare'},
    {'code': 'SIMA', 'symbol': 'SIMA.JK', 'name': 'Siwani Makmur', 'sector': 'Basic Materials'},
    {'code': 'SIMP', 'symbol': 'SIMP.JK', 'name': 'Salim Ivomas Pratama (Minyak Bimoli)', 'sector': 'Agriculture & CPO'},
    {'code': 'SINI', 'symbol': 'SINI.JK', 'name': 'Singaraja Putra (Tambang Batubara)', 'sector': 'Energy & Mining'},
    {'code': 'SIPD', 'symbol': 'SIPD.JK', 'name': 'Sreeya Sewu Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'SKBM', 'symbol': 'SKBM.JK', 'name': 'Sekar Bumi (Makanan Laut Beku)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'SKLT', 'symbol': 'SKLT.JK', 'name': 'Sekar Laut (Kerupuk Finna)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'SKRN', 'symbol': 'SKRN.JK', 'name': 'Superkrane Mitra Utama (Rental Crane)', 'sector': 'Industrials'},
    {'code': 'SLIS', 'symbol': 'SLIS.JK', 'name': 'Gaya Abadi Sempurna (Motor Listrik Selis)', 'sector': 'Consumer Cyclicals'},
    {'code': 'SMAR', 'symbol': 'SMAR.JK', 'name': 'Smart (Sinar Mas Agro Resources and Technology)', 'sector': 'Agriculture & CPO'},
    {'code': 'SMBR', 'symbol': 'SMBR.JK', 'name': 'Semen Baturaja (SIG Group)', 'sector': 'Basic Materials'},
    {'code': 'SMDM', 'symbol': 'SMDM.JK', 'name': 'Suryamas Dutamakmur (Rancamaya)', 'sector': 'Properties'},
    {'code': 'SMDR', 'symbol': 'SMDR.JK', 'name': 'Samudera Indonesia (Pelayaran Logistik)', 'sector': 'Industrials'},
    {'code': 'SMGA', 'symbol': 'SMGA.JK', 'name': 'Sumber Mineral Global Abadi', 'sector': 'Basic Materials'},
    {'code': 'SMGR', 'symbol': 'SMGR.JK', 'name': 'Semen Indonesia (SIG/Semen Gresik)', 'sector': 'Basic Materials'},
    {'code': 'SMIL', 'symbol': 'SMIL.JK', 'name': 'Sarana Mitra Luas (Forklift Rental)', 'sector': 'Industrials'},
    {'code': 'SMKL', 'symbol': 'SMKL.JK', 'name': 'Satyamitra Kemas Lestari', 'sector': 'Basic Materials'},
    {'code': 'SMKM', 'symbol': 'SMKM.JK', 'name': 'Sumber Mas Konstruksi', 'sector': 'Infrastructures'},
    {'code': 'SMMA', 'symbol': 'SMMA.JK', 'name': 'Sinar Mas Multiartha', 'sector': 'Financials'},
    {'code': 'SMMT', 'symbol': 'SMMT.JK', 'name': 'Golden Eagle Energy (Rajawali Group)', 'sector': 'Energy & Mining'},
    {'code': 'SMRA', 'symbol': 'SMRA.JK', 'name': 'Summarecon Agung (Summarecon Kelapa Gading/Serpong)', 'sector': 'Properties'},
    {'code': 'SMRU', 'symbol': 'SMRU.JK', 'name': 'SMR Utama', 'sector': 'Energy & Mining'},
    {'code': 'SMSM', 'symbol': 'SMSM.JK', 'name': 'Selamat Sempurna (Filter Sakura)', 'sector': 'Consumer Cyclicals'},
    {'code': 'SNLK', 'symbol': 'SNLK.JK', 'name': 'Sunter Lake Hotel', 'sector': 'Consumer Cyclicals'},
    {'code': 'SOCI', 'symbol': 'SOCI.JK', 'name': 'Soechi Lines (Kapal Tanker Minyak)', 'sector': 'Industrials'},
    {'code': 'SOFA', 'symbol': 'SOFA.JK', 'name': 'Boston Furniture Industries', 'sector': 'Consumer Cyclicals'},
    {'code': 'SOHO', 'symbol': 'SOHO.JK', 'name': 'Soho Global Health (Imboost/Curcuma)', 'sector': 'Healthcare'},
    {'code': 'SONA', 'symbol': 'SONA.JK', 'name': 'Sona Topas Tourism Industry', 'sector': 'Consumer Cyclicals'},
    {'code': 'SOSS', 'symbol': 'SOSS.JK', 'name': 'Shield On Service', 'sector': 'Industrials'},
    {'code': 'SOTS', 'symbol': 'SOTS.JK', 'name': 'Satria Mega Kencana', 'sector': 'Consumer Cyclicals'},
    {'code': 'SPMA', 'symbol': 'SPMA.JK', 'name': 'Suparma (Tissue Plenty)', 'sector': 'Basic Materials'},
    {'code': 'SPTO', 'symbol': 'SPTO.JK', 'name': 'Surya Pertiwi (Sanitary TOTO Indonesia)', 'sector': 'Basic Materials'},
    {'code': 'SQMI', 'symbol': 'SQMI.JK', 'name': 'Wilton Makmur Indonesia (Tambang Emas)', 'sector': 'Basic Materials'},
    {'code': 'SRTG', 'symbol': 'SRTG.JK', 'name': 'Saratoga Investama Sedaya (Sandiaga/Edwin)', 'sector': 'Financials'},
    {'code': 'SSIA', 'symbol': 'SSIA.JK', 'name': 'Surya Semesta Internusa (Subang Smartpolitan)', 'sector': 'Properties'},
    {'code': 'SSMS', 'symbol': 'SSMS.JK', 'name': 'Sawit Sumbermas Sarana', 'sector': 'Agriculture & CPO'},
    {'code': 'SSTM', 'symbol': 'SSTM.JK', 'name': 'Sunson Textile Manufacturer', 'sector': 'Consumer Cyclicals'},
    {'code': 'STAA', 'symbol': 'STAA.JK', 'name': 'Sumber Tani Agung Resources', 'sector': 'Agriculture & CPO'},
    {'code': 'STAR', 'symbol': 'STAR.JK', 'name': 'Buana Artha Anugerah', 'sector': 'Financials'},
    {'code': 'STRK', 'symbol': 'STRK.JK', 'name': 'Lovina Beach Brewery', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'STTP', 'symbol': 'STTP.JK', 'name': 'Siantar Top (Snack Goriorio/Mie Gemez)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'SUGI', 'symbol': 'SUGI.JK', 'name': 'Sugih Energy', 'sector': 'Energy & Mining'},
    {'code': 'SULI', 'symbol': 'SULI.JK', 'name': 'SLJ Global (Kayu Lapis/Plywood)', 'sector': 'Basic Materials'},
    {'code': 'SUMI', 'symbol': 'SUMI.JK', 'name': 'Sumisho Global Logistics Indonesia', 'sector': 'Industrials'},
    {'code': 'SUNU', 'symbol': 'SUNU.JK', 'name': 'Surya Nusatama (Transport)', 'sector': 'Industrials'},
    {'code': 'SUPR', 'symbol': 'SUPR.JK', 'name': 'Solusi Tunas Pratama (Tower Protelindo)', 'sector': 'Telco & Infra'},
    {'code': 'SURE', 'symbol': 'SURE.JK', 'name': 'Super Energy (Gas Bumi)', 'sector': 'Energy & Mining'},
    {'code': 'SWID', 'symbol': 'SWID.JK', 'name': 'Saraswanti Indoland Development', 'sector': 'Properties'},
    {'code': 'TALF', 'symbol': 'TALF.JK', 'name': 'Tunas Alfin (Kemasan Foil)', 'sector': 'Basic Materials'},
    {'code': 'TAMA', 'symbol': 'TAMA.JK', 'name': 'Lancartama Sejati', 'sector': 'Infrastructures'},
    {'code': 'TAMU', 'symbol': 'TAMU.JK', 'name': 'Pelayaran Tamarin Samudra', 'sector': 'Energy & Mining'},
    {'code': 'TAPG', 'symbol': 'TAPG.JK', 'name': 'Triputra Agro Persada (TP Rachmat Group)', 'sector': 'Agriculture & CPO'},
    {'code': 'TARA', 'symbol': 'TARA.JK', 'name': 'Agung Semesta Sejahtera', 'sector': 'Properties'},
    {'code': 'TAXI', 'symbol': 'TAXI.JK', 'name': 'Express Transindo Utama (Taksi Express)', 'sector': 'Industrials'},
    {'code': 'TBIG', 'symbol': 'TBIG.JK', 'name': 'Tower Bersama Infrastructure', 'sector': 'Telco & Infra'},
    {'code': 'TBLA', 'symbol': 'TBLA.JK', 'name': 'Tunas Baru Lampung (Gula Rose Brand/Minyak)', 'sector': 'Agriculture & CPO'},
    {'code': 'TBMS', 'symbol': 'TBMS.JK', 'name': 'Tembaga Mulia Semanan (Kabel Tembaga)', 'sector': 'Basic Materials'},
    {'code': 'TCID', 'symbol': 'TCID.JK', 'name': 'Mandom Indonesia (Gatsby/Pixy)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'TCPI', 'symbol': 'TCPI.JK', 'name': 'Transcoal Pratama', 'sector': 'Industrials'},
    {'code': 'TDPM', 'symbol': 'TDPM.JK', 'name': 'Tridomain Performance Materials', 'sector': 'Basic Materials'},
    {'code': 'TEBE', 'symbol': 'TEBE.JK', 'name': 'Dana Brata Luhur (Pelabuhan Batubara)', 'sector': 'Energy & Mining'},
    {'code': 'TECH', 'symbol': 'TECH.JK', 'name': 'Indosterling Technomedia', 'sector': 'Technology'},
    {'code': 'TELE', 'symbol': 'TELE.JK', 'name': 'Tiphone Mobile Indonesia', 'sector': 'Telco & Infra'},
    {'code': 'TFAS', 'symbol': 'TFAS.JK', 'name': 'Telefast Indonesia', 'sector': 'Technology'},
    {'code': 'TFCO', 'symbol': 'TFCO.JK', 'name': 'Tifico Fiber Indonesia', 'sector': 'Basic Materials'},
    {'code': 'TGKA', 'symbol': 'TGKA.JK', 'name': 'Tigaraksa Satria (Distribusi Susu/SGM)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'TGRA', 'symbol': 'TGRA.JK', 'name': 'Terregra Asia Energy (Pembangkit EBT)', 'sector': 'Infrastructures'},
    {'code': 'TIFA', 'symbol': 'TIFA.JK', 'name': 'KDB Tifa Finance', 'sector': 'Financials'},
    {'code': 'TIMS', 'symbol': 'TIMS.JK', 'name': 'Timah Industri', 'sector': 'Basic Materials'},
    {'code': 'TINS', 'symbol': 'TINS.JK', 'name': 'Timah (MIND ID Group)', 'sector': 'Basic Materials'},
    {'code': 'TIRA', 'symbol': 'TIRA.JK', 'name': 'Tira Austenite', 'sector': 'Basic Materials'},
    {'code': 'TIRT', 'symbol': 'TIRT.JK', 'name': 'Tirta Mahakam Resources', 'sector': 'Basic Materials'},
    {'code': 'TKIM', 'symbol': 'TKIM.JK', 'name': 'Pabrik Kertas Tjiwi Kimia (Sinar Mas)', 'sector': 'Basic Materials'},
    {'code': 'TLDN', 'symbol': 'TLDN.JK', 'name': 'Teladan Prima Agro (Kelapa Sawit)', 'sector': 'Agriculture & CPO'},
    {'code': 'TLKM', 'symbol': 'TLKM.JK', 'name': 'Telkom Indonesia (Telkomsel/IndiHome)', 'sector': 'Telco & Infra'},
    {'code': 'TMAS', 'symbol': 'TMAS.JK', 'name': 'Temas (Pelayaran Peti Kemas)', 'sector': 'Industrials'},
    {'code': 'TMPO', 'symbol': 'TMPO.JK', 'name': 'Tempo Inti Media (Majalah Tempo)', 'sector': 'Consumer Cyclicals'},
    {'code': 'TNCA', 'symbol': 'TNCA.JK', 'name': 'Trimuda Nuansa Citra (Garuda Express)', 'sector': 'Industrials'},
    {'code': 'TOBA', 'symbol': 'TOBA.JK', 'name': 'TBS Energi Utama (Motor Listrik Electrum/LBP)', 'sector': 'Energy & Mining'},
    {'code': 'TOOL', 'symbol': 'TOOL.JK', 'name': 'Penta Prima Sejati', 'sector': 'Industrials'},
    {'code': 'TOSK', 'symbol': 'TOSK.JK', 'name': 'Topindo Solusi Komunika', 'sector': 'Technology'},
    {'code': 'TOTO', 'symbol': 'TOTO.JK', 'name': 'Surya Pertiwi (TOTO Sanitary)', 'sector': 'Basic Materials'},
    {'code': 'TOWR', 'symbol': 'TOWR.JK', 'name': 'Sarana Menara Nusantara (Djarum Group)', 'sector': 'Telco & Infra'},
    {'code': 'TOYS', 'symbol': 'TOYS.JK', 'name': 'Sunindo Adipersada (Boneka Mainan)', 'sector': 'Consumer Cyclicals'},
    {'code': 'TPIA', 'symbol': 'TPIA.JK', 'name': 'Chandra Asri Pacific (Prajogo Pangestu)', 'sector': 'Basic Materials'},
    {'code': 'TPMA', 'symbol': 'TPMA.JK', 'name': 'Trans Power Marine (Tongkang Batubara)', 'sector': 'Industrials'},
    {'code': 'TRAIN', 'symbol': 'TRAIN.JK', 'name': 'Kereta Api Pariwisata (KAI)', 'sector': 'Industrials'},
    {'code': 'TRGU', 'symbol': 'TRGU.JK', 'name': 'Cerestar Indonesia (Tepung Terigu)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'TRIL', 'symbol': 'TRIL.JK', 'name': 'Triwira Insanlestari', 'sector': 'Energy & Mining'},
    {'code': 'TRIM', 'symbol': 'TRIM.JK', 'name': 'Trimegah Sekuritas Indonesia (Boy Thohir)', 'sector': 'Financials'},
    {'code': 'TRIN', 'symbol': 'TRIN.JK', 'name': 'Perintis Triniti Properti (Triniti Land)', 'sector': 'Properties'},
    {'code': 'TRIO', 'symbol': 'TRIO.JK', 'name': 'Trikomsel Oke', 'sector': 'Telco & Infra'},
    {'code': 'TRIS', 'symbol': 'TRIS.JK', 'name': 'Trisula International', 'sector': 'Consumer Cyclicals'},
    {'code': 'TRJA', 'symbol': 'TRJA.JK', 'name': 'Transkon Jaya (Rental Kendaraan Tambang)', 'sector': 'Industrials'},
    {'code': 'TRON', 'symbol': 'TRON.JK', 'name': 'Teknologi Karya Digital Nusa (IoT Transportasi)', 'sector': 'Technology'},
    {'code': 'TRST', 'symbol': 'TRST.JK', 'name': 'Trias Sentosa (Plastik Film BOPP)', 'sector': 'Basic Materials'},
    {'code': 'TRUE', 'symbol': 'TRUE.JK', 'name': 'Triniti Dinamik', 'sector': 'Properties'},
    {'code': 'TRUK', 'symbol': 'TRUK.JK', 'name': 'Guna Timur Raya', 'sector': 'Industrials'},
    {'code': 'TRUS', 'symbol': 'TRUS.JK', 'name': 'Trust Finance Indonesia', 'sector': 'Financials'},
    {'code': 'TSPC', 'symbol': 'TSPC.JK', 'name': 'Tempo Scan Pacific (Bodrex/Hemaviton)', 'sector': 'Healthcare'},
    {'code': 'TUGU', 'symbol': 'TUGU.JK', 'name': 'Asuransi Tugu Pratama Indonesia (Pertamina)', 'sector': 'Financials'},
    {'code': 'TYRE', 'symbol': 'TYRE.JK', 'name': 'King Tire Indonesia (Ban Kingland)', 'sector': 'Consumer Cyclicals'},
    {'code': 'UCID', 'symbol': 'UCID.JK', 'name': 'Uni-Charm Indonesia (MamyPoko/Charm)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'UFOE', 'symbol': 'UFOE.JK', 'name': 'Damai Sejahtera Abadi (UFO Elektronika)', 'sector': 'Consumer Cyclicals'},
    {'code': 'ULTJ', 'symbol': 'ULTJ.JK', 'name': 'Ultra Jaya Milk Industry (Susu Ultra/Teh Kotak)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'UNIC', 'symbol': 'UNIC.JK', 'name': 'Unggul Indah Cahaya (Alkilbenzena)', 'sector': 'Basic Materials'},
    {'code': 'UNIQ', 'symbol': 'UNIQ.JK', 'name': 'Ulima Nitra (Jasa Tambang)', 'sector': 'Energy & Mining'},
    {'code': 'UNIT', 'symbol': 'UNIT.JK', 'name': 'Nusantara Inti Corpora', 'sector': 'Consumer Cyclicals'},
    {'code': 'UNTR', 'symbol': 'UNTR.JK', 'name': 'United Tractors (Komatsu/PAMA/Tuprag Gold)', 'sector': 'Industrials'},
    {'code': 'UNVR', 'symbol': 'UNVR.JK', 'name': 'Unilever Indonesia (Pepsodent/Lifebuoy/Sunlight)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'URBN', 'symbol': 'URBN.JK', 'name': 'Urban Jakarta Propertindo (LRT City)', 'sector': 'Properties'},
    {'code': 'UVCR', 'symbol': 'UVCR.JK', 'name': 'Trimegah Karya Pratama (Ultra Voucher)', 'sector': 'Technology'},
    {'code': 'VAST', 'symbol': 'VAST.JK', 'name': 'Vastland Indonesia (Gudang Logistik)', 'sector': 'Properties'},
    {'code': 'VBLM', 'symbol': 'VBLM.JK', 'name': 'Victoria Berkat Lestari Mandiri', 'sector': 'Financials'},
    {'code': 'VCII', 'symbol': 'VCII.JK', 'name': 'Victoria Care Indonesia (Ovale/Miranda)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'VERN', 'symbol': 'VERN.JK', 'name': 'Verena Multi Finance', 'sector': 'Financials'},
    {'code': 'VICI', 'symbol': 'VICI.JK', 'name': 'Victoria Care Indonesia', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'VICO', 'symbol': 'VICO.JK', 'name': 'Victoria Investama', 'sector': 'Financials'},
    {'code': 'VINS', 'symbol': 'VINS.JK', 'name': 'Victoria Insurance', 'sector': 'Financials'},
    {'code': 'VIVA', 'symbol': 'VIVA.JK', 'name': 'Visi Media Asia (tvOne/ANTV)', 'sector': 'Consumer Cyclicals'},
    {'code': 'VKTR', 'symbol': 'VKTR.JK', 'name': 'VKTR Teknologi Mobilitas (Bus Listrik Bakrie/BYD)', 'sector': 'Consumer Cyclicals'},
    {'code': 'VOKS', 'symbol': 'VOKS.JK', 'name': 'Voksel Electric (Kabel Listrik)', 'sector': 'Basic Materials'},
    {'code': 'VRNA', 'symbol': 'VRNA.JK', 'name': 'Mizuho Balimor Finance', 'sector': 'Financials'},
    {'code': 'VTNY', 'symbol': 'VTNY.JK', 'name': 'Venteny Fortuna International', 'sector': 'Technology'},
    {'code': 'WAPO', 'symbol': 'WAPO.JK', 'name': 'Wahana Pronatural', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'WEGE', 'symbol': 'WEGE.JK', 'name': 'Wijaya Karya Bangunan Gedung', 'sector': 'Infrastructures'},
    {'code': 'WEHA', 'symbol': 'WEHA.JK', 'name': 'WEHA Transportasi Indonesia (White Horse)', 'sector': 'Industrials'},
    {'code': 'WGSH', 'symbol': 'WGSH.JK', 'name': 'Wira Global Solusi (Venture Builder)', 'sector': 'Technology'},
    {'code': 'WICO', 'symbol': 'WICO.JK', 'name': 'Wicaksana Overseas International', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'WIDI', 'symbol': 'WIDI.JK', 'name': 'Widiant Jaya Krenindo (Rental Alat Berat)', 'sector': 'Industrials'},
    {'code': 'WIFI', 'symbol': 'WIFI.JK', 'name': 'Solusi Sinergi Digital (Surge/Fiber Optic KAI)', 'sector': 'Telco & Infra'},
    {'code': 'WIKA', 'symbol': 'WIKA.JK', 'name': 'Wijaya Karya (Persero)', 'sector': 'Infrastructures'},
    {'code': 'WINE', 'symbol': 'WINE.JK', 'name': 'Hatten Bali (Wine Lokal Bali)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'WINR', 'symbol': 'WINR.JK', 'name': 'Winner Nusantara Jaya', 'sector': 'Properties'},
    {'code': 'WINS', 'symbol': 'WINS.JK', 'name': 'Wintermar Offshore Marine (Kapal Offshore)', 'sector': 'Energy & Mining'},
    {'code': 'WIRG', 'symbol': 'WIRG.JK', 'name': 'WIR ASIA (Metaverse/AR Technology)', 'sector': 'Technology'},
    {'code': 'WMPP', 'symbol': 'WMPP.JK', 'name': 'Widodo Makmur Perkasa (Peternakan Sapi)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'WMUU', 'symbol': 'WMUU.JK', 'name': 'Widodo Makmur Unggas (Ayam)', 'sector': 'Consumer Non-Cyclicals'},
    {'code': 'WOOD', 'symbol': 'WOOD.JK', 'name': 'Integra Indocabinet (Furnitur Kayu Ekspor)', 'sector': 'Consumer Cyclicals'},
    {'code': 'WOWS', 'symbol': 'WOWS.JK', 'name': 'Ginting Jaya Energi (Rig Migas)', 'sector': 'Energy & Mining'},
    {'code': 'WSBP', 'symbol': 'WSBP.JK', 'name': 'Waskita Beton Precast', 'sector': 'Basic Materials'},
    {'code': 'WSKT', 'symbol': 'WSKT.JK', 'name': 'Waskita Karya (Persero)', 'sector': 'Infrastructures'},
    {'code': 'WTON', 'symbol': 'WTON.JK', 'name': 'Wijaya Karya Beton (WIKA Beton)', 'sector': 'Basic Materials'},
    {'code': 'YELO', 'symbol': 'YELO.JK', 'name': 'Yelooo Integra Datanet (Passpod)', 'sector': 'Technology'},
    {'code': 'YPAS', 'symbol': 'YPAS.JK', 'name': 'Yanaprima Hastapersada', 'sector': 'Basic Materials'},
    {'code': 'YULE', 'symbol': 'YULE.JK', 'name': 'Yulie Sekuritas Indonesia', 'sector': 'Financials'},
    {'code': 'ZATA', 'symbol': 'ZATA.JK', 'name': 'Bersama Zatta Jaya (Elzatta Hijab)', 'sector': 'Consumer Cyclicals'},
    {'code': 'ZBRA', 'symbol': 'ZBRA.JK', 'name': 'Dosni Roha Indonesia (DNR Logistics)', 'sector': 'Industrials'},
    {'code': 'ZINC', 'symbol': 'ZINC.JK', 'name': 'Kapuas Prima Coal (Seng/Timbal)', 'sector': 'Basic Materials'},
    {'code': 'ZONE', 'symbol': 'ZONE.JK', 'name': 'Mega Perintis (Manzone/MOC)', 'sector': 'Consumer Cyclicals'},
    {'code': 'ZYRX', 'symbol': 'ZYRX.JK', 'name': 'Zyrexindo Mandiri Buana (Laptop Zyrex)', 'sector': 'Technology'}
]
